datalad/datalad-next

.github/workflows/test_crippledfs.yml, datalad_next/__init__.py, datalad_next/patches/__init__.py, datalad_next/patches/create_sibling_ghlike.py, datalad_next/patches/tests/test_create_sibling_ghlike.py
The switch makes the storage of a newly entered credential
conditional on a successful authorization, in the spirit of
datalad/datalad#3126.
Moreover, stored credentials now contain a `realm` property that identified the API endpoint. This makes it possible to identify candidates of suitable credentials without having to specific their name, similar to a request context url used by the old providers setup.
This automatic realm-based credential lookup is now also implemented. When no credential name is specified, the most recently used credential matching the API realm will be used automatically. If determined like this, it will be tested for successfull authorization, and will then be stored again with an updated 'last-used' timestamp.
This is the rest of the functionality from …
=> Patch core's create-sibling-ghlike to use new credential system

datalad_next/credman.py, datalad_next/tests/test_credman.py
Also improve logging, and make sure the 'last-used' timestamp is actually updated (even when already present).
=> Fix and verify support for credentials with '.' in the name

datalad_next/tests/utils.py
This PR fixes issue #10
The reason for the stalling tests was the main thread could not successfully connect to the WebDAV-server when the server was still in the process of binding the socket address and starting to listen on the socket. The situation could occur when the server-thread was not finished with the socket setup while the main thread already tried to connect to the server.
This is fixed now by performing the server socket setup before starting the server-thread and before returning to the main thread
=> Fix test stalling

datalad_next/__init__.py, datalad_next/create_sibling_webdav.py, datalad_next/http_support.py, datalad_next/tests/test_create_sibling_webdav.py, datalad_next/tests/utils.py, setup.cfg
This PR introduces the command `create-sibling-webdav`, which creates a set of two remotes, one for git annex export and one for datalad push.
- One is called <name>-vcs and is meant to contain the git-repository info.
- The other one is called <name>-tree and is meant to contain the annex-exported tree.
Credential manager is still "datalad.downloaders.credentials.UserPassword".
The siblings are meant to be used with a publish dependency
=> Add a first version of create-sibling-webdav

datalad_next/create_sibling_webdav.py, datalad_next/gitremote/datalad_annex.py, datalad_next/tests/test_create_sibling_webdav.py, datalad_next/utils.py
This homogenized the code between create_sibling_webdav() and the more
generic `datalad-annex::` git remote helper.
=> Use common helper get_specialremote_credential_properties()

datalad_next/create_sibling_webdav.py, datalad_next/gitremote/datalad_annex.py, datalad_next/gitremote/tests/test_datalad_annex.py, datalad_next/patches/__init__.py, datalad_next/patches/annexrepo.py, datalad_next/patches/create_sibling_ghlike.py, datalad_next/patches/siblings.py, datalad_next/tests/test_create_sibling_webdav.py, datalad_next/utils.py
Does not yet allow for manual credential entry on `enable_remote()`
=> Auto-deploy credentials on `AnnexRepo.enable_remote()` (and with it also `siblings enable`)

datalad_next/create_sibling_webdav.py, datalad_next/tests/test_create_sibling_webdav.py
This commit fixes a number of TODO-items. Some are left to be addressed by the implementation of the `--existing`-
and the `--dry-run`-switches.
=> Fix TODO-items in `create_sibling_webdav`

datalad_next/create_sibling_webdav.py
This is no meaningfully defined behavior (discussed elsewhere).
Extracted from https://github.com/datalad/datalad-next/pull/21
=> Strip existing=None possibility from Parameter constraint

datalad_next/create_sibling_webdav.py, datalad_next/tests/test_create_sibling_webdav.py
- when a credential is not given, auto-discovery is wanted, and not just for the initial create, but also for any subsequent git-operation
- specifically test scenarios with declared vs. discovered credentials
- define desired behavior in docs
- test with credential name that needs to be URL-encoded
=> Complete desired credential handling for `create_sibling_webdav()`

datalad_next/create_sibling_webdav.py, datalad_next/tests/test_create_sibling_webdav.py
This turns
```
% datalad create-sibling-webdav 'https://fz-juelich.sciebo.de/remote.php/dav/files/m.hanke%40fz-juelich.de/dummy'
create_sibling_webdav.storage(ok): /tmp/dummy (dataset)
[INFO   ] Configure additional publication dependency on "fz-juelich.sciebo.de-storage"
[INFO   ] Could not enable annex remote fz-juelich.sciebo.de. This is expected if fz-juelich.sciebo.de is a pure Git remote, or happens if it is not accessible.
[WARNING] Could not detect whether fz-juelich.sciebo.de carries an annex. If fz-juelich.sciebo.de is a pure Git remote, this is expected. Remote was marked by annex as annex-ignore. Edit .git/config to reset if you think that was done by mistake due to absent connection etc
...
```
into
```
% datalad create-sibling-webdav …
```
=> Preset WebDAV Git sibling to 'annex-ignore'

datalad_next/create_sibling_webdav.py, datalad_next/tests/test_create_sibling_webdav.py
- Changes default for `--existing` to `error`
- Adds discovery of not yet enabled special remotes with conflicting names
- `existing=skip` skips the creation of the "conflicting" remote not the entire dataset. Meaning: A possibly specified storage sibling would be skipped independently on whether or not the git remote is skipped. Not sure whether that is advantageous or not. WDYT on that aspect, @mih, @mslw ?
- the above also somewhat implies that there are up to two results per dataset
=> Implement --existing for create-sibling-webdav

datalad_next/create_sibling_webdav.py, datalad_next/tests/test_create_sibling_webdav.py
Unifies and enriches result records of `create-sibling-webdav` and adds a custom result renderer that is roughly resembling the one of `siblings`.
Closes #33
Closes #38
This needs rebasing. Last three commits are relevant ATM.
=> Fix create-sibling-webdav results

datalad_next/patches/push_to_export_remote.py
This commit add documentatin that describes how
push behaves if a git-annex special remote is
configured with "exporttree=yes".
=> extend push to to describe export behavior

datalad_next/patches/tests/test_push_to_export_remote.py
This PR should a test that fails in git workflows of datalad-extensions: https://github.com/datalad/datalad-extensions/pull/97
=> improve logger.debug call validation in test

datalad_next/patches/push_to_export_remote.py
With Git 2.36.0, git-annex 10.20220504, and datalad-next 0.2.2, pushing to an exporttree remote (created with create_sibling_webdav --mode filetree) resulted in:
```
CommandError: 'git -c diff.ignoreSubmodules=none cat-file blob git-annex:export.log' failed with exitcode 128
fatal: path 'export.log' does not exist in 'git-annex'
```
This is because the error message produced by git cat-file changed somewhere between Git 2.30 ("fatal: Not a valid object name git-annex:export.log") and 2.36 ("fatal: path 'export.log' does not exist in 'git-annex'").
Because CI installs new git-annex & Git versions, this error was actually caught in unrelated PRs #58 and #60 but it was not clear from CI output alone. Merging will should make CI go green again on those (after re-running).
Fixes #62
=> Fix error handling for cat-file on newer Git

.appveyor.yml, README.md, datalad_next/patches/__init__.py, datalad_next/patches/push_optimize.py, datalad_next/patches/tests/test_push.py
This change introduces a replacement for core's `push.py:_push()`
with a more intelligible flow. It replaces the stalled
https://github.com/datalad/datalad/pull/6666
Importantly, it makes one behavior change, which is desirable IMHO.
Instead of rejecting to git-push any refspec for a repo with a detached
HEAD, it will attempt to push a git-annex branch for an AnnexRepo. The
respective test that ensured this behavior beyond the particular
conditions the original problem occurred in was adjusted accordingly.
`push` tests from core are imported and executed to ensure
proper functioning.
Summary of the original commits patching the core implementation.
- Consolidate publication dependency handling in one place
- Consolidate tracking of git-push-dryrun exec
Make a failed attempt discriminable …
=> Make push avoid refspec handling for special remote push targets

datalad_next/gitremote/datalad_annex.py
This is no longer possible with git-annex 10.20220505 and later.
Ideally, we would get this feature back. See
https://git-annex.branchable.com/bugs/10.20220525_cannot_probe_for_untrusted_remote_key/
But for now a forced-download will have to do.
Closes datalad/datalad-next#72
=> (Temporarily?) discontinue probing remotes for XDLRA--refs

datalad_next/gitremote/datalad_annex.py
This avoids the complications with changing behavior of `git-annex-fsck`
with 10.20220525 (see
https://github.com/datalad/datalad-next/issues/72).  Moreover, it allows
for moving to an opportunistic download that just tries, instead of
having to check with the remote first. This saves a request, and should
translate to measurable speed-up for slow remotes (e.g. WebDAV).
Closes datalad/datalad-next#75
=> Switch `datalad-annex::` to use git-annex plumbing 'transferkey'

datalad_next/gitremote/datalad_annex.py, datalad_next/gitremote/tests/test_datalad_annex.py
#26 is still valid with today's git-annex. This PR implements a rather draconian workaround: Instead of dropping the repoannex keys, it wipes out the entire object tree of the local `repoannex` utility repo.
This is possible, because this utility repo is constructed on the fly from the URL specification, and only contains the two keys that need to be dropped. However, given the bluntness of the approach, it is limited to the platform on which the original issue is happening: windows.
=> Enable full feature-set for `datalad-annex::` on windows

.zenodo.json, CITATION.cff
This PR adds `zenodo.json` & `citation.cff` files. Closes #79 
I made several assumptions in compiling the files:
- I included everyone listed by GitHub in the project's contributors page, and used alphabetical order
- I used the corresponding files from datalad repo to get affiliations & orcids, and other datalad projects or GitHub profiles if you weren't there
- ~I only listed first names in `citation.cff`, partially because that's how it's done in datalad repo, partially because I wasn't sure on correct spelling (e.g. comma or no comma between names)~
- I unified the FZJ affiliation (to be spelled "Research Centre Jülich")
- from the tags proposed in extension template, I used the two first, "data management" and "data distribution".
Please correct me if there's something you'd want to …
=> Add citation

.github/PULL_REQUEST_TEMPLATE.md, changelog.d/README, changelog.d/scriv.ini, changelog.d/templates/entry_title.md.j2, changelog.d/templates/new_fragment.md.j2
This change provides everything necessary to allow developers to use
https://github.com/nedbat/scriv to provide changelog items.
In contrast to the practice in datalad-core, this neither means
recycling commit messages, nor C&P from PR descriptions.
The basic goals for an appropriate changelog are:
1. Changelog items target users, not developers, hence should be
written for this audience specifically
2. A changelog should give any user a reasonably self-contained
description.
Workflow:
1. A changeset is composed in an arbitrary way, typically posted
as a PR.
2. At any time before a merge, a developer can run
`scriv create` to generate a pre-formatted changelog snippet.
3. This snippet can be processed/edited in any way a developer
sees fit (with scriv --add/edit or without), as long as it …
=> Aid changelog composition via `scriv`

changelog.d/20220714_135722_michael.hanke_token.md, datalad_next/patches/create_sibling_ghlike.py
Before there would be no trace of the nature of this error.
The tests don't cover it, because in -core credentials without a name
are not even a thing.
=> Add missing import and log particular exception for credential failure

datalad_next/conftest.py
DataLad 0.17.0 came with pytest. earlier versions are not maintained.
To avoid needing to troubleshoot why testing works in unexpected ways
(may be import failed for some reason for newer datalad), just use
standard setup_package without try/except
motivator, likely unrelated but who knows -- https://github.com/datalad/datalad-extensions/runs/7775998620?check_suite_focus=true fail with
```
2022-08-10T21:15:20.6557615Z AssertionError: Got 0 instead of 1 expected results matching
2022-08-10T21:15:20.6557848Z   {
2022-08-10T21:15:20.6558033Z    "action": "publish",
2022-08-10T21:15:20.6558322Z    "message": "There is no active branch, cannot determine remote branch",
2022-08-10T21:15:20.6558643Z    "path": "/tmp/datalad_temp_test_gh1811zo1ei755",
2022-08-10T21:15:20.6558892Z    "status": …
```
=> RF: do not bother with shim for setup_package

changelog.d/20220812_190404_benjaminpoldrack_fix_push_patch.md, datalad_next/patches/push_to_export_remote.py, datalad_next/patches/tests/test_push_to_export_remote.py
The push-to-export-remote patch of core's push command failed to handle
the results from `AnnexRepo._call_annex_records_items_` correctly.
It was not accounting for the fact, that this are JSON records as
reported by git-annex (thus ignoring a bunch of fields), which should be
done by `datalad.interface.results.annexjson2result`.
Furthermore it was unconditionally setting the status to `ok` expecting
a `CommandError` otherwise. This is not how the generator works in the
general case, though. It does yield `error` records and proceeds if it
can. `CommandError` still can happen but it's not the only thing leading
to an error result.
This led to `push` always "succeeding" with an `ok` result, rendering
all tests of export remotes useless, that rely on `push` failing if
there was something …
=> Fix results when pushing to export remote

datalad_next/create_sibling_webdav.py, datalad_next/patches/annexrepo.py
This is done elsewhere already. There is no point in selective local importing.
Fixes datalad/datalad-next#28
=> Consolidate mock.patch import to top-level

.appveyor.yml, tools/coverage-bin/datalad, tools/coverage-bin/git-annex-remote-datalad, tools/coverage-bin/git-annex-remote-datalad-archives, tools/coverage-bin/git-annex-remote-ora
We arrived at some fairly intrusive patching of datalad-core. We can no longer rely on spot-checking for intentional behavior changes, but must also look for unintentional ones.
This changes adds five appveyor runs (split in order to keep the total runtime low) to cover the datalad-core test suite on the oldest support Python version.
I added support for keyword-based selection/exclusion of tests, because core has some tests which must not run, because the verify broken or intentionally changes behavior.
=> Expand testing of (patched) datalad-core

changelog.d/20220818_082902_michael.hanke_bf_97.md, datalad_next/patches/create_sibling_ghlike.py
Otherwise a freshly entered token would have a proper realm configured
(and work smoothly), but be prone to naming conflicts.
Fixes datalad/datalad-next#97
=> Make sure a token secret always has a non-None name

changelog.d/20220824_140528_m.szczepanik_credentials_example.md, datalad_next/credentials.py
This adds an example of how to set a new credential of type user_password, with a given user property, to the examples in the
credentials command. For some reason, I always had to think twice before adding a new user_password credentials based on the existing docs (maybe it's just me). I thought this usage could have an explicit example.
The added example shows that type and user need to be defined as properties, and entry of the secret is interactive. While it was probably clear from the other examples and command description, now it's explicit. Also, it is the first example where more than one property is being given.
=> DOC: Add an example of adding a user_password credential

datalad_next/gitremote/datalad_annex.py
It turns the documentation note into a piece of code that
would reveal an issue in debug mode (at least).
Ping datalad/datalad-next#104
=> Add a warning on old git-annex versions to datalad-annex::

datalad_next/patches/__init__.py, datalad_next/patches/clone.py, datalad_next/patches/clone_ephemeral.py, datalad_next/patches/clone_ria.py, datalad_next/patches/clone_utils.py
The series provides a patch to replace `clone_dataset()` the key workhorse of datalad-core's `clone` command. The patch causes no change to any functionality, but refactors the code from large monolithic functions into significantly smaller, more comprehensible units. Emphasis is made on separating function that control the flow of processing (`patches/clone.py`) from utilities that perform focused tasks (`patches/clone_utils.py`).
Key feature of the refactoring is the provisioning of a set of dedicated function that implement particular stages of the clone and post-clone setup processing:
- `_try_clone_candidates()` (the main clone attempt loop)
- `_try_clone_candidate()` (handle a single clone attempt)
- `_try_git_clone_candidate()` (only workhorse ATM with all git-clone specifics)
- …
=> Make `clone_dataset()` patchable

datalad_next/credman.py
The `title` parameter of `ui.question` is intended for the prompting text, which is somewhat misleading by name.
In opposition to the `Credential`'s in datalad core, the CredentialManager splits the prompting text and the input retrieval when asking for a property or secret by calling `ui.message` and then `ui.question`. While this is kinda fine with CLI, other `ui` backends like gooey can't handle this properly. In combination with patching `create-sibling-ghlike` this led to https://github.com/datalad/datalad-gooey/issues/340.
=> Don't split prompt and question in CredentialManager

changelog.d/20221118_111838_michael.hanke_runnerbuf.md, datalad_next/patches/__init__.py, datalad_next/patches/runnerthreads.py
This has a dramatic effect on the throughput, i.e. when using `ThreadedRunner()` for SSH-based downloads.
=> Patch datalad.runner.runnerthreads.ReadThread to use shutil buffer size default

datalad_next/credentials.py, datalad_next/credman.py, datalad_next/tests/test_credentials.py, datalad_next/tests/test_credman.py
This change enables users and commands to leave a credential name unspecified. If possible (interactive session), a user will be prompted for a name (until a unique name was entered), or "skip" was indicated.
If entering a credential name is not possible, a `ValueError` is raised.
`CredentialManager.set()` is enhanced with an additional `_context` argument that is included in a name prompt to provide context to a user what kind of credential is being saved. Calling commands typically have a better idea on that vs barfing a potentially complex credential with all properties in the terminal.
A new `_suggested_name` argument for `CredentialManager.set()` can be used by callers to suggest a default name. If the suggestion conflicts with an existing credential it is ignored.
Closes …
=> Let `credentials()` and `CredentialManager.set()` prompt for name

datalad_next/constraints/base.py, datalad_next/create_sibling_webdav.py, datalad_next/credentials.py, datalad_next/dataset.py, datalad_next/download.py, datalad_next/patches/clone.py, datalad_next/patches/clone_ephemeral.py, datalad_next/patches/clone_ria.py, datalad_next/patches/clone_utils.py, datalad_next/patches/configuration.py, datalad_next/patches/interface_utils.py, datalad_next/patches/push_optimize.py, datalad_next/patches/push_to_export_remote.py, datalad_next/patches/tests/test_push.py, datalad_next/tests/test_create_sibling_webdav.py, datalad_next/tests/test_credman.py, datalad_next/tests/test_tree.py, datalad_next/tree.py
This is the start of migrating away from historical pieces in `datalad.distribution.dataset`, eventually making the entire module obsolete.
Ping https://github.com/datalad/datalad-next/issues/139
=> Consolidate `Dataset` import on `datalad_next.dataset`

datalad_next/exceptions.py, datalad_next/tests/utils.py, datalad_next/url_operations/__init__.py, datalad_next/url_operations/file.py, datalad_next/url_operations/http.py, datalad_next/url_operations/ssh.py, datalad_next/url_operations/tests/test_any.py, datalad_next/url_operations/tests/test_file.py, datalad_next/url_operations/tests/test_http.py, datalad_next/url_operations/tests/test_ssh.py
When a URL works in principle, but points to something that is just not there (e.g. HTTP404) vs we cannot tell right now (HTTP5xx, or network down). This now raises `AccessFailedError` for a general error and `UrlTargetNotFound` for a 404-like error.
This is needed for a reliable operation of CHECKPRESENT in git-annex special remotes, and for meaningful error reporting in general.
This changeset also include dedicated unit tests for `UrlOperations`.
Closes #148
=> `UrlOperations` distinguish between connection-error and not-found

datalad_next/url_operations/__init__.py, datalad_next/url_operations/any.py, datalad_next/url_operations/file.py, datalad_next/url_operations/http.py, datalad_next/url_operations/ssh.py, datalad_next/url_operations/tests/test_ssh.py
This PR adds triggering and handling of CommandError, and timeout handling to `SshUrlOperations.upload()`.
A `timeout`-keyword argument is added to the `UrlOperations`-interface.
In addition, there are some type-definition fixes, as well as:
-  raise an exception if `from_path` in `SshUrlOperations.upload()` is `None`, because the method does not properly support uploading from stdin.
=> Add command error and timeout handling to ssh upload 

.github/workflows/docbuild.yml, datalad_next/annexremote/__init__.py, datalad_next/annexremote/tests/test_uncurl.py, datalad_next/annexremote/uncurl.py, docs/source/index.rst, setup.cfg
=> 'uncurl' special remote 

datalad_next/url_operations/__init__.py, datalad_next/url_operations/ssh.py, datalad_next/url_operations/tests/test_ssh.py
This PR enables `SshUrlOperations.upload()` to use stdin as upload source, as documented in the `UrlOperations.upload()` interface description. A test is provided.
The code assumes that `datalad_next.url_operations._progress_report_start` is capable of handling an `expected_size` of `None`, and that this triggers a report for an upload of unknown size.
=> Add support for ssh upload from stdin

datalad_next/url_operations/ssh.py
This PR fixes a bug that was triggered when an annexremote process uses ssh to communicate with a remote.
The issue was the the annexremote process would not receive all data that was sent over stdin. The reason for that was that the ssh-subprocesses inherit stdin from the parant process, i.e. from annexremote, and suck in data before the annexremote can read it. This is due to a `None`-argument in the subprocess.Popen stdin keyword argument. That leads to the subprocess inheriting stdin from the parent process. Instead `subprocess.DEVNULL`, would be a proper argument.
This should fix the error discussed in PR #159 and also appears in PR #164
=> fix a bug where ssh subprocesses steal stdin

datalad_next/create_sibling_webdav.py, datalad_next/credentials.py, datalad_next/tree.py
as long as `require_dataset()` is still provided upstream), and in `datalad_next.patches` (for compatibility).
It shall never be introduced in other places again. `datalad_next.constraints.dataset.EnsureDataset` can and must be used now.
Closes #139
=> Remove `require_dataset()` usage from codebase

datalad_next/url_operations/file.py
`Path.unlink()` only has `missing_ok` since PY3.8. But there desired `missing_ok=False` is and was the default behavior. The underlying effects are tested, hence we can simply remove the argument.
=> Reestablish PY3.7 compat

datalad_next/url_operations/any.py, datalad_next/url_operations/tests/test_any.py
Previously, the dict based on which `AnyUrlOperations` selects a handler must contain a handler class as values. This made it necessary to import everything first, and thereby creates an avoidable startup cost.
Now one declares a tuple with a module name and a class name to import on demand as values.
This avoids unconditional dependencies on special interest packages.
Closes datalad/datalad-next#175
=> Importless declaration of URL handler

datalad_next/commands/__init__.py, datalad_next/commands/credentials.py, datalad_next/commands/download.py, datalad_next/commands/tests/test_create_sibling_webdav.py, datalad_next/commands/tests/test_credentials.py, datalad_next/constraints/basic.py, datalad_next/constraints/compound.py, datalad_next/constraints/parameter.py, datalad_next/constraints/tests/test_cmdarg_validation.py, datalad_next/constraints/tests/test_special_purpose.py, datalad_next/patches/interface_utils.py
This provides a solution to the `EnsureMappings` proposal from datalad/datalad-gooey#311, albeit in a command-specific fashion.
This now establishes an interface to perform additional validation steps (uniformly across all APIs) after per-parameter validation was completed successfully.
The underlying validator class could also be a source for documentation to be exposed to users via the help-generation tooling, but this is not done here, because they largely sit in datalad-core.
The utility of this approach is demo'ed on the `credentials` command, which moves information from one parameter to another, depending on the origin API. This is fully captured, and no validation or type conversiion code remains in the actual command implementation (`__call__`).
The impact on implementation …
=> Joint validation of a full command parameterization 

datalad_next/commands/__init__.py, datalad_next/patches/interface_utils.py
This is a companion PR to https://github.com/datalad/datalad/pull/7170 to be merged upon a new DataLad release, when tests will start raising deprecation warnigns. If you'd like a changelog entry, please let me know.
- Closes #182
=> Account for internal eval_results method move in next's imports

datalad_next/patches/annexrepo.py, datalad_next/patches/clone.py, datalad_next/patches/clone_ephemeral.py, datalad_next/patches/clone_ria.py, datalad_next/patches/distribution_dataset.py, datalad_next/patches/interface_utils.py, datalad_next/patches/push_optimize.py, datalad_next/patches/push_to_export_remote.py, datalad_next/patches/runnerthreads.py, datalad_next/patches/siblings.py, datalad_next/patches/tests/test_push_to_export_remote.py, datalad_next/utils/patch.py
Among other things is defaults to raising an exception when a patch target is not found. This should better prevent invalid patching attempts due to unexpected changes in the patch target.
=> Introduce `apply_patch()` helper

datalad_next/commands/create_sibling_webdav.py, datalad_next/commands/tests/test_create_sibling_webdav.py, datalad_next/utils/credman.py, datalad_next/utils/tests/test_credman.py
See docstring for details.
This replaces a more specific implementation in the context of `create_sibling_webdav()`, and is now available as a more generic helper for use in other scenarios too.
=> CredentialManager.obtain() helper for a standard credential workflow

datalad_next/url_operations/any.py, datalad_next/url_operations/tests/test_any.py
Here is an example:
```cfg
[datalad "url-handler.(^|.*::)s3://mybucket/"]
class = datalad_next.url_operations.fsspec.FsspecUrlOperations
kwargs = {\"fs_kwargs\": {\"s3\": {\"anon\": false}}}
```
This defines a dedicated handler for accessing the AWS S3 bucket
'mybucket', and turns off anonymous access for this bucket specifically.
A regex-match expression is directly included in the config subsection
name (following the pattern of the standard Git `url.<base>.insteadOf`
configuration pattern).
The only mandatory configuration property is `class`. It points to an
importable class implementing the `UrlOperations` API.
If necessary, arbitrary keyword-arguments for the class constructur
can be specified, JSON-encoded, in a `kwargs` configuration item.
On instantiating the `AnyUrlOperations` …
=> Loading URL handlers from configuration 

datalad_next/commands/create_sibling_webdav.py, datalad_next/commands/tests/test_create_sibling_webdav.py, datalad_next/constraints/dataset.py, datalad_next/constraints/parameter.py, datalad_next/constraints/tests/test_special_purpose.py
This change addresses a key shortcoming of the new command parameter
validation approach. Previously, it did not process a parameter's
default value (at all), and required each command implementation to
handle a default value directly.
This caused an inconvenience for the ubiquitous `dataset` parameter,
which often defaults to `None` to indicate "will discover in CWD".
However, given that `None` is the default, this discovery would need
to be implemented in each command, rather than using the standard
`EnsureDataset`.
With this change, `EnsureCommandParameterization` can be
parameterized with a new `validate_defaults` argument to cause
processing of an individual parameter's default.
Here, this is implemented for the `create_sibling_webdav()` command
as a demonstration. Likely other …
=> Allow for opt-in parameter default validation

README.md, datalad_next/annexremotes/uncurl.py, datalad_next/url_operations/__init__.py, datalad_next/url_operations/any.py, datalad_next/url_operations/file.py, datalad_next/url_operations/http.py, datalad_next/url_operations/ssh.py, datalad_next/url_operations/tests/test_any.py, datalad_next/url_operations/tests/test_file.py, datalad_next/url_operations/tests/test_http.py, datalad_next/url_operations/tests/test_ssh.py
This should be more commonly understood.
Closes #219
=> Rename URL operation `sniff()` -> `stat()`

datalad_next/patches/create_sibling_ghlike.py
Previously, when a credential was auto-discovered or entered -- but then access failed -- identical errors meesages were produced:
> Credential <credential name> did not yield successful authorization
without any advice on what to do.
With this change, the error message is different, depending on whether a credential was automatically determined from a query, or whether it was entered manually right before the access attempt. Now it would say:
Auto-selected existing credential:
> Auto-selected <credential name> did not yield successful authorization.
Please select a different credential via the `credential` option of
this command, or remove/edit the credential with the DataLad command
`credentials`.
Entered credential:
> Entered <credential name> did not yield successful authorization. …
=> Improve credential errors for github-likes

.appveyor.yml, datalad_next/annexremotes/tests/test_uncurl.py, datalad_next/commands/tests/test_download.py, datalad_next/tests/utils.py, datalad_next/url_operations/tests/test_http.py, tools/appveyor/docker-load-httpbin
Improve the test reliability by making it less dependent on the public
instance.
This change enables this for the standard Ubuntu CI run on appveyor. Others could follow, but for now it is most important to have a single run be unaffected to be able to tell false positives.
Closes #236
=> Deploy dedicated HTTPBIN instance

.github/workflows/test_crippledfs.yml
Like it is done on appveyor. This should also be faster that adding all of NeuroDebian
=> Use datalad-installer for git-annex on GitHub actions

.github/workflows/test_crippledfs.yml
This should be more reliable than the performance of the public instance.
=> Deploy dedicated httpbin instance on GitHub actions

.github/workflows/test_crippledfs.yml
At least in terms of success or failure of a workflow. See inside for reasoning.
=> Make gathering coverage stats and their submission a nice to have

datalad_next/constraints/base.py, datalad_next/constraints/compound.py, datalad_next/constraints/parameter.py, datalad_next/constraints/tests/test_compound.py, datalad_next/constraints/tests/test_special_purpose.py
Type annotation fixes and generally bring things into a more sensible, more documented, more tested state.
=> New ConstraintWithPassthrough

datalad_next/utils/requests_auth.py
Previously, the last used credential matching a `realm` was used unconditionally. With this change all matching credentials are filtered to exclude any credentials without a secret set.
A secret might not be present for any reason (removed by an external process, or never set to begin with). Regardless of the cause for such an anomaly, such a credential can never work for authentication. Therefore, we exclude them immediately. Should no other credential matching a realm provide a secret, prompting for credential entry is attempted.
Closes #245
=> Only work for complete credentials in `DataladAuth`

datalad_next/credman/manager.py, datalad_next/credman/tests/test_credman.py
Trying to find what is happening with #249 by making the implemented logic less complex.
=> RF of `CredentialManager.get()` related code

datalad_next/credman/manager.py
- Uniform means to determine a secret.
- Use those means in `set()` too
- Document oddities
- No change in behavior
=> More `CredentialManager` RF

datalad_next/commands/tests/test_credentials.py, datalad_next/conftest.py, datalad_next/credman/tests/test_credman.py, datalad_next/tests/utils.py
This fixture provides an isolated keyring in-memory-only backend for tests that needs to store/retrieve credentials.
The fixture is function-scope, hence the backend is destroyed at the end of each test.
Closes https://github.com/datalad/datalad/issues/7295
=> New `memory_keyring` fixture

datalad_next/commands/credentials.py, datalad_next/commands/tests/test_download.py
When called with `dataset=None`, `credentials()` would auto-locate
a dataset containing CWD (and use its configuration), whereas
`download()` would use the global configuration in this case.
This change makes the behavior uniform and chooses what `download()`
did as the model behavior.
This uniformatization is meaningful on its own.
However, due to datalad/datalad#7299 it is
also a necessity, because otherwise credentials deposited by
`download()` remain invisible to `credentials()` -- which is the
superficial trigger for datalad#249
Closes datalad#249
=> Make dataset-lookup behavior of `credentials` identical to `download` 

datalad_next/credman/manager.py, datalad_next/credman/tests/test_credman.py
For now the only scenario is a credential specification that comprises a token-property only.
However, with the recent RF there is now a dedicated piece of code that could be extended arbitrarily to support additional scenarios.
```
❯ DATALAD_CREDENTIAL_MIKE_TOKEN=some dl -f json_pp credentials get mike
{
"action": "credentials",
"cred_secret": "some",
"cred_type": "token",
"name": "mike",
"status": "ok"
}
```
Closes #251
=> Do credential type detection for reporting

datalad_next/constraints/parameter.py, datalad_next/constraints/tests/test_cmdarg_validation.py, datalad_next/constraints/tests/test_exceptions.py
This exposes a, so far dormant, feature of the `Constraint` class to
parameter validation: constraint tailoring for particular datasets.
`EnsureCommandParameterization` learned a `tailor_for_dataset` parameter
that can be used to identify which parameters' constraints should be
tailored for which `Dataset` instances. Tailoring will only be actually
done under the following conditions:
- the dataset-providing parameters need to evaluate to a
DatasetParameter instance, typically via `EnsureDataset`
(all regular conditions apply, e.g. a default `None` not being processed
etc)
- the to-be-tailored parameter `Constraint` needs to implement its
`for_dataset()` method to perform a tailoring.
A test with some custom-made constraints is included. At the moment,
no production-ready constraints do …
=> On-demand constraint-tailoring to dataset arguments

datalad_next/commands/tests/test_create_sibling_webdav.py, datalad_next/commands/tests/test_credentials.py, datalad_next/conftest.py, datalad_next/credman/tests/test_credman.py, datalad_next/gitremotes/tests/test_datalad_annex.py, datalad_next/tests/utils.py
The background for this is https://github.com/datalad/datalad/issues/7297
TODO
=> Prevent undesired configuration modifications by tests

datalad_next/patches/interface_utils.py
fixes #266
This piece of code was not able to handle DatasetParameter objects, and instead crash with a ValueError. This patch should fix this.
=> BF: Teach _execute_command to handle DatasetParameters

datalad_next/constraints/base.py, datalad_next/constraints/compound.py
This is important for debugging. It will now reveal the contained constraints' `__repr__()` output.
=> Give compound constraints a comprehensive `__repr__`

datalad_next/constraints/compound.py, datalad_next/constraints/tests/test_compound.py
Previously, any invalid input caused an immediate and unrecoverable stop and raise.
However for any batch mode application it is essential to be able to ignore errors and/or simply report on them
This change adds an option to yield (not raise) any occuring internal exception. This is straightforward to distinuish from regular items. They can be reraised outside, or ignored, or reported on.
Closes #273
=> Make `EnsureGeneratorFromFileLike` more suitable for batch-mode use

datalad_next/commands/tree.py, datalad_next/constraints/basic.py, datalad_next/url_operations/__init__.py, datalad_next/utils/requests_auth.py
This is now establishing a uniform PEP 604 style `X | None` notation in the code base.
Closes #153
=> Rectify implicit optional type annotation

datalad_next/commands/download.py, datalad_next/constraints/__init__.py, datalad_next/constraints/base.py, datalad_next/constraints/tests/test_base.py, datalad_next/constraints/tests/test_cmdarg_validation.py
Both implementations performed in-place modifications of the left-side constraint. This is not appropriate, because it matches the semantics of `__iand__` and `__ior__`, rather than `__and__` and `__or__`.
This change move away from the in-place implementation and simply returns a new instance. This is cheap.
There is no implementation of `__iadd__` and `__ior__`, although simply renaming the methods would have been enough.
There is no need for it, and it can be done whenever there is actual demand.
Closes #291
=> Rectify OR and AND of `Constraints` and `AltConstraints`

datalad_next/constraints/__init__.py, datalad_next/constraints/base.py, datalad_next/constraints/compound.py, datalad_next/constraints/tests/test_compound.py
See the individual commit descriptions for details
Closes #267 
Closes #286
=> Enable customization of `Constraint` descriptions, standardize access

datalad_next/annexremotes/tests/test_uncurl.py, datalad_next/commands/tests/test_create_sibling_webdav.py, datalad_next/conftest.py, datalad_next/constraints/tests/test_basic.py, datalad_next/constraints/tests/test_cmdarg_validation.py, datalad_next/constraints/tests/test_compound.py, datalad_next/credman/tests/test_credman.py, datalad_next/patches/tests/test_configuration.py, datalad_next/patches/tests/test_create_sibling_ghlike.py, datalad_next/patches/tests/test_push.py, datalad_next/tests/fixtures.py
The can perform most dataset-related setup used in tests. Both fixtures are function-scope, to limit cross-contamination of tests.
More of the already included test-simplifications become possible, once `serve_path_via*` are also proper fixtures.
Closes #293
=> Test fixtured `dataset` and `existing_dataset`

datalad_next/commands/tests/test_create_sibling_webdav.py, datalad_next/conftest.py, datalad_next/credman/tests/test_credman.py, datalad_next/gitremotes/tests/test_datalad_annex.py, datalad_next/tests/fixtures.py, datalad_next/tests/test_testutils.py, datalad_next/tests/utils.py
=> New `webdav_server` fixture

datalad_next/commands/tests/test_download.py, datalad_next/conftest.py, datalad_next/gitremotes/tests/test_datalad_annex.py, datalad_next/tests/fixtures.py, datalad_next/tests/utils.py
This removes the last traces of its usage and simplifies associated tests.
Closes #295
=> `serve_path_via_http` -> `http_server` pytest fixture

docs/source/annex-backends.rst, docs/source/annex-specialremotes.rst, docs/source/api.rst, docs/source/cmd.rst, docs/source/developer_guide/constraints.rst, docs/source/developer_guide/contributing.rst, docs/source/developer_guide/index.rst, docs/source/git-remote-helpers.rst, docs/source/index.rst, docs/source/patches.rst, docs/source/pyutils.rst
#274 highlighted the need to have developer-targeted docs on how to implement constraints. I took this opportunity to start a Developer Guide in the docs, that can serve as a place for such implementation guidelines. 
In order to better find this Guide, I decluttered the side bar into the topical headings of the index page.
TODOs
=> DOC: Declutter the sidebar and start a developer guide

datalad_next/__init__.py, datalad_next/commands/download.py, datalad_next/commands/tests/test_create_sibling_webdav.py, datalad_next/constraints/base.py, datalad_next/constraints/compound.py, datalad_next/constraints/exceptions.py, datalad_next/constraints/formats.py, datalad_next/constraints/parameter.py, datalad_next/constraints/tests/test_cmdarg_validation.py, datalad_next/constraints/tests/test_exceptions.py, datalad_next/constraints/tests/test_special_purpose.py, datalad_next/patches/interface_utils.py, datalad_next/url_operations/__init__.py
Elevate level of possible error message customizations. This is best demo'ed using the included update of the `download` command.
Prior to this PR, a typical error for the violation of a complex constraint would look like this:
```
❯ datalad download wurst
[ERROR  ] 1 command parameter constraint violation
spec
not any of [AnyOf(EnsureMapping(key=EnsureURL(), value=AnyOf(EnsureValue(), EnsurePath()), delimiter=' '), AllOf(AnyOf(EnsureJSON(), EnsureURLFilenamePairFromURL()), EnsureMapping(key=EnsureURL(), value=AnyOf(EnsureValue(), EnsurePath()), delimiter=' '))), EnsureListOf(item_constraint=AnyOf(EnsureMapping(key=EnsureURL(), value=AnyOf(EnsureValue(), EnsurePath()), delimiter=' '), AllOf(AnyOf(EnsureJSON(), EnsureURLFilenamePairFromURL()), EnsureMapping(key=EnsureURL(), …
```
=> Structured error reporting and customized rendering of parameter violations

datalad_next/constraints/basic.py
I thought I found a small TODO to help with, but then realized that the code already does what the TODO wants. So instead, I've added an example how to do it.
=> Replace implementation TODO with example how it already works

datalad_next/annexremotes/tests/test_uncurl.py
=> public url would be https while docker http, so allow for both in test matching

datalad_next/conftest.py, datalad_next/tests/fixtures.py
It appears that these workers are more or less constantly blocked. There
is little point in all these false-positive failures.
The respective tests will continue to run on appveyor, but limited to
deployments with a dedicated docker-instance of httpbin running as
part of the CI setup (this is ubuntu for now).
=> Give up on httpbin access from appveyor

changelog.d/20230505_074522_michael.hanke_httphdrs.md, datalad_next/url_operations/http.py, datalad_next/url_operations/tests/test_http.py
This only required to expose the headers as a constructor argument of `HttpUrlOperations`. With that change, the existing customization functionality was already sufficient to achieve the goal.
A test is included.
Closes #336
=> Enabled configuration-based HTTP request header customization

changelog.d/20230508_072605_michael.hanke_cerror.md, datalad_next/constraints/__init__.py, datalad_next/constraints/basic.py, datalad_next/constraints/compound.py, datalad_next/constraints/dataset.py, datalad_next/constraints/exceptions.py, datalad_next/constraints/git.py, datalad_next/constraints/tests/test_basic.py, datalad_next/constraints/tests/test_compound.py, datalad_next/constraints/tests/test_special_purpose.py
This makes it compatible with command parameter validation and auto-generated error messages.
- Closes #341
- Closes #275
=> Convert `Constraint`s to `raise_for()` to raise `ConstraintError`

datalad_next/__init__.py, datalad_next/commands/__init__.py, datalad_next/commands/ls_file_collection.py, datalad_next/commands/tests/test_ls_file_collection.py, datalad_next/conftest.py, datalad_next/constraints/parameter.py, datalad_next/constraints/tests/test_cmdarg_validation.py, datalad_next/iter_collections/__init__.py, datalad_next/iter_collections/directory.py, datalad_next/iter_collections/tarfile.py, datalad_next/iter_collections/tests/test_iterdir.py, datalad_next/iter_collections/tests/test_itertar.py, datalad_next/iter_collections/utils.py, docs/source/api.rst, docs/source/cmd.rst, docs/source/pyutils.rst
This PR is making `add-archive-content` (largely) obsolete. Closes #183 
Summary
- new module `iter_collections` to establish a location in the spirit of #323 . The idea is to use dataclasses instead of result records, and enums instead of string labels to report on collection content. Iterators also support hashing (as means to generate identifiers.
- import `iterdir()` from `datalad-gooey` as an iterator for a directory as a collections (of directory content)
- implemented `itertar()` for tar file archives -- reporting aligned with `iterdir()`
- `ls-file-collection` command that can drive these iterators.
- factors any glue code necessary into a custom validator 
- converts collection iterator items into result records and yields them
This is somewhat in conflict with #342 due to …
=> `iter_collections` and `ls-file-collection`

datalad_next/constraints/git.py, datalad_next/exceptions/__init__.py, datalad_next/gitremotes/datalad_annex.py, datalad_next/patches/push_optimize.py, datalad_next/patches/push_to_export_remote.py, datalad_next/patches/tests/test_push_to_export_remote.py, datalad_next/runners/__init__.py, datalad_next/runners/protocols.py, datalad_next/url_operations/ssh.py
From now on, all relevant pieces are contained in, and are to be imported from `datalad_next.runners`
Closes #355
Ping @christian-monch
=> Centralize imports and additions to and from `datalad.runner`

datalad_next/constraints/exceptions.py, datalad_next/constraints/parameter.py, datalad_next/constraints/tests/test_cmdarg_validation.py, datalad_next/patches/interface_utils.py
Previously a missing argument would cause a validation error via a side-effect, and only crash once an insufficient parameterization actually hits a command. This led to confusion error messages, such as:
```
CommandParametrizationError: 0 command parameter constraint violation
```
Whereas the CLI would produce something like
```
error: the following arguments are required: ...
```
via `argparse.
With this change, missing argument detection is now explicitly supported. And looks like:
```
CommandParametrizationError: 1 command parameter constraint violation
type=<no value>, collection=<no value>
missing arguments
```
For that a number of changes had to be implemented:
- The patch of `get_allargs_as_kwargs()` now also makes it report required arguments of a callable.
- The patch of …
=> Support missing argument reporting in `EnsureCommandParameterization`

datalad_next/commands/ls_file_collection.py, datalad_next/iter_collections/directory.py, datalad_next/iter_collections/tarfile.py, datalad_next/iter_collections/tests/test_iterdir.py, datalad_next/iter_collections/tests/test_itertar.py, datalad_next/iter_collections/utils.py
This enables something like this:
```
In [1]: from pydicom import dcmread
In [2]: from datalad_next.iter_collections.tarfile import iter_tar
In [3]: for i in iter_tar('/tmp/icfstore/dl-Z03/P000624_dicom.tar'):
...:     if i.fp:
...:         with dcmread(i.fp) as dcm:
...:             ...
```
Or in other words, arbitrary (post-)processing of files in a collection.
Here is a concrete use case that is enabled by this change: https://github.com/psychoinformatics-de/inm-icf-utilities/pull/6/commits/01349d87d34ec415dc55dd9b432fb8ffdebf9865
I had the concern that moving the hashing logic out of the iterators would remove the ability to not compute a particular hash, if the collection readily provides it (think dataverse offering MD5s). However, that is not true. Any such collection could provide …
=> Enhance `FileSystemItem` and `iter_tar|dir()` to provide file IO

datalad_next/url_operations/http.py, datalad_next/url_operations/tests/test_http.py
Previously, a file downloaded from a server that supported `deflate`, or other types of compressions would end up in compressed form on disk. This is undesirable, as it changes the nature of files on download.
This change:
- adds a test that documents the faulty behavior, and the fix
- enables transparent decoding of compressed streams on download
- adjusts progress reporting to focus on bytes transferred, not bytes decompressed
- discontinued the use of `requests_toolbelt.downloadutils.tee`, arguably, using this (minimal) helper just makes things more opaque
Closes #364
=> `HttpUrlOperations` decompresses download with appropriate encoding

datalad_next/config/__init__.py, datalad_next/credman/manager.py, datalad_next/credman/tests/test_credman.py, datalad_next/url_operations/__init__.py, datalad_next/url_operations/any.py, docs/source/pyutils.rst
This will be the cannonical import location. This changeset starts using that for imports that are presently focused on type-annotation.
Closes #337 
This change was pulled from https://github.com/datalad/datalad-next/pull/339 -- which stalled and is now blocking this fix.
=> Establish `datalad_next.config` for `ConfigManager`

datalad_next/types/archivist.py, datalad_next/types/enums.py, datalad_next/types/tests/test_archivist.py, docs/source/pyutils.rst
These are the `dl+archive:...` style URLs used by the `datalad-archives` special remote and by the upcoming `archivist`.
This also brings an ENUM for archive types, and a place to put other enums too.
=> Explicit type for archive locators

datalad_next/types/annexkey.py, datalad_next/types/tests/test_annexkey.py
I would think that using this type as a key in a mapping would be a standard use case. This would mean that post-init assignment of properties is not possible. I tend to think that this is OK.
Closes #379
=> Make `AnnexKey` hashable

changelog.d/20230527_000546_christian.moench_bf_type_error.md, datalad_next/utils/requests_auth.py
This PR replaces the faulty CredentialManager annotation for the cfg-parameter of DataladAuth.__init__() with the correct type, i.e. ConfigManager.
=> Fix type annotation for `cfg`-parameter in `DataladAuth.__init__()`

changelog.d/20230530_084701_michael.hanke.md, datalad_next/patches/__init__.py, datalad_next/patches/commanderror.py, datalad_next/patches/tests/test_commanderror.py, datalad_next/runners/__init__.py
`CommandError`, the standard exception raised for any non-zero exit command execution now reports which command failed with `repr()` too. Previously, only `str()` would produce an informative message about a failure, while `repr()` would report `CommandError('')`, unless a dedicated message was provided.
Changes:
```
Could not obtain 'MD5E-s20--7fecdac24beaba574b1e9d7ff9da67f8.csv' -caused by- Exhausted all candidate archive handlers (previous failures [CommandError('')])
```
to
```
Could not obtain 'MD5E-s20--7fecdac24beaba574b1e9d7ff9da67f8.csv' -caused by- CommandError: 'git -c diff.ignoreSubmodules=none annex contentlocation MD5E-s391--15a48a2cb9efbdedece04ff16be413e9.tar.gz -c annex.dotfiles=true' failed with exitcode 1
```
Ping @christian-monch -- should likely also be done in …
=> `repr(CommandError(...))` now informative

datalad_next/annexremotes/__init__.py, datalad_next/annexremotes/uncurl.py, datalad_next/datasets/__init__.py, docs/source/annex-specialremotes.rst, docs/source/pyutils.rst
Also includes
- `SpecialRemote.repo` property to provide `LeanAnnexRepo` instance on demand
- `SpecialRemote.remotename` property
- `SpecialRemote.get_remote_gitcfg()` as a standard method to query special remote configuration from git configuration -- set by remote, or by remote type (e.g., all `uncurl` remotes).
=> Team up `LeanGitRepo` with `LeanAnnexRepo` and other standardizations for `SpecialRemote`

datalad_next/__init__.py, datalad_next/annexremotes/archivist.py, datalad_next/annexremotes/tests/test_archivist.py, datalad_next/runners/exceptions.py, datalad_next/runners/tests/test_exceptions.py, docs/source/annex-specialremotes.rst, setup.cfg, tools/coverage-bin/git-annex-remote-archivist
This is a replacement for the implementation of the `datalad-archives` remote. In addition to its predecessor, it reduces the storage overhead from 200% to 100% by doing partial extraction from fully downloaded archives.
Ultimately, it will support sparse/partial access to remote archives, avoiding any storage overhead, and the requirement to unconditionally download full archives (see https://github.com/datalad/datalad-next/pull/215).
This implementation is trying to be efficient by:
- trying to fulfill requests using locally present archives
- trying to download smaller archives before larger ones
This implementation is aiming to be extensible by:
- using `ArchiveOperations` as a framework to uniformly implement (partial) access to local (or remote) archives.
This addresses #185
TODO: …
=> `archivist` git-annex special remote

datalad_next/commands/__init__.py, datalad_next/patches/interface_utils.py
This avoids a deprecation warning on each and every load.
=> We depend on datalad 0.18.4, no need to account for pre 0.18

datalad_next/annexremotes/archivist.py, datalad_next/annexremotes/tests/test_archivist.py
In INM-ICF-utilities, a get operations on a directory with many files from the same tarball failed after the first file was successfully retrieved. Debugging revealed that the internal retrieval of the tar archive was attempted for this first try successfully. Later files retried retrieval unnecessarily, resulting in cryptic errors downstream
ping @mih 
Backstory: INM-ICF-utilities can operate on files indexed with the archivist special remote from a tarball. When none of the files or archive content was locally present yet, a ``get`` of several files at once resulted in errors like this:
```
id not complete successfully")
E           datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 22 failed:
E           [{'action': 'get',
E …
```
=> BF: cache archivist handler for later reuse

datalad_next/config/tests/test_core.py
Requires additional protection of the test config against modification. Required in datalad-next, but undetected in datalad-core.
=> Import and run datalad-core tests for `ConfigManager`

.appveyor.yml, datalad_next/config/tests/test_utils.py, datalad_next/config/utils.py, datalad_next/patches/cli_configoverrides.py, datalad_next/patches/enabled.py, datalad_next/patches/tests/test_cli_configoverrides.py
This achieve the main goal of making any `datalad -c ...` specification
affect not just the datalad-specific config in the main Python process,
but can now handle *any* Git config, and also impact the behavior of
any subprocesses.
Furthermore this handling is extended to cover also `DATALAD_...`
ENV variables, including `DATALAD_CONFIG_OVERRIDES_JSON`.
Within the session `ConfigManager` instance the behavior is now more
uniform. `ConfigManager.overrides` are now exclusively instance-specific
overrides -- matching their description and implementation. No
configuration override coming from CLI or process ENV is reflected in
`ConfigManager.overrides` anymore.
Closes #325 -- although the scope is a bit broader.
This changeset defers the need to address #397, but does not resolve it.
Ideally …
=> Patch CLI to post any config overrides in Git-native fashion in ENV

datalad_next/iter_collections/utils.py
Originally introduced in
https://github.com/datalad/datalad-next/pull/361, but a need for this has also been expressed elsewhere, hence now a standalone changeset.
These types could also move into `datalad_next.types...`
=> Diversify `Item` type classes

datalad_next/url_operations/http.py, datalad_next/url_operations/tests/test_http.py, datalad_next/utils/requests_auth.py
This PR inserts information about the protection realm into the credential prompt for 401-error handling. This allows a user to enter a credential matching the protection realm.
RFC 2617 defines the protection realm as follows:
> The realm directive (case-insensitive) is required for all
> authentication schemes that issue a challenge. The realm value
> (case-sensitive), in combination with the canonical root URL (the
> absoluteURI for the server whose abs_path is empty; see section 5.1.[2](https://datatracker.ietf.org/doc/html/rfc2617#ref-2)
> of [2]) of the server being accessed, defines the protection space.
> These realms allow the protected resources on a server to be
> partitioned into a set of protection spaces, each with its own
> authentication scheme and/or authorization …
=> Show realm in credential prompt

.appveyor.yml, datalad_next/archive_operations/__init__.py, datalad_next/archive_operations/tarfile.py, datalad_next/archive_operations/tests/test_tarfile.py
- More sensible `__repr__` for `ArchiveOperations`
- Document methods
- More flexible handling of archive item names. `open()` and all other
such methods can now accept `item.name` from `__iter__` results
directly. Based on the assumption that all TAR archives use member
names in POSIX notation.
- Add unit tests with comprehensive coverage. Modelled after the
`ZipArchiveOperations` tests in
datalad#407 but with more
context manager use.
<details>
<summary>Stuff from the development history of this PR</summary>
Interesting test failure pattern:
```
FAILED ../archive_operations/tests/test_tarfile.py::test_tararchive_iterator - AssertionError: assert 'test-archive/' in <datalad_next.archive_operations.tarfile.TarArchiveOperations object at 0x108f29fd0>
```
It is only happening with PY3.8, …
=> Update TarArchiveOperations and equip with tests 

datalad_next/iter_collections/gitworktree.py, datalad_next/iter_collections/tests/test_itergitworktree.py
This PR modifies the regular expression that is used during execution of `iter_gitworktree()` in order to parse the output of `git ls-tree`. 
The current version ensures that only one tab-character is considered to separate the file info from the file name. That ensures that file names that start with tab-characters are properly handled (the previous version,  would consider all tab-characters, including the tab-characters belonging to the name, as file-info/file-name separator).
The PR includes a regression test that verifies correct handling of file names starting with tab-characters
=> Fix `git ls-file` parsing in `iter_gitworktree()`

datalad_next/iter_collections/tests/test_iterzip.py, datalad_next/iter_collections/zipfile.py
This PR modifies zip-iterators to use `PurePosixPath` for names of archive members instead of `PurePath`. The rationale for this change is that according to [zip-APPNOTE.TXT version 6.3.3](https://pkware.cachefly.net/webdocs/APPNOTE/APPNOTE-6.3.3.TXT) from September 1st, 2012, all slashes in file names (contained in zip) _must_ be forward slashes, i.e. '/'. From September 26th, 2006 onwards [zip-APPNOTE.TXT version 6.3.0](https://pkware.cachefly.net/webdocs/APPNOTE/APPNOTE-6.3.0.TXT) states that all slashes _should_ be forward slashes.
It seems to be safe to assume that almost all zip-files we encounter will be using forward slashes. Because `PurePath` instances are OS-specific, a `PurePath` on Windows will contain `\`-slashes and not properly represent the content of the archive. …
=> Use PurePosixPath for names of zipfile-entries (or even better: `str`)?

datalad_next/archive_operations/__init__.py, datalad_next/archive_operations/tarfile.py
Fixes #406 
This PR implements solution 3. described in item #406.
It changes the return type of the method `open()` of `ArchiveOperations` and its subclasses to reflect the return type that is defined in the method code. That means the return type is changed to `Generator`.
The PR also introduces a complete doc-string for `TarArchiveOperations.open()` to describe the return types that are observed y the caller of `open()` on an instance of `TarArchiveOperations`. Due to the use of the `@contextmanager`-decorator, the return type observed by a caller is `IO | None` instead of `Generator`.
=> Use correct return type of `ArchiveOperations.open()` to `Generator`

tools/appveyor/install-syspkgs
Currently the construction of the test environment on appveyor is failing in debian-based environments. It fails during `apt-get update` due to changed release infos for debian packages. This PR allows allows `apt-get update` to continue in changes in release info. This should fix the tests on debian-based appveyor environments.
=> Fix package installation in appveyor on debian platforms

datalad_next/commands/tests/test_credentials.py, datalad_next/commands/tests/test_download.py, datalad_next/conftest.py, datalad_next/credman/tests/test_credman.py, datalad_next/tests/fixtures.py, datalad_next/tests/utils.py
Replacement for `with_testsui`
This provides two fixtures
- `datalad_interactive_ui`
- `datalad_noninteractive_ui`
that can be used to test user interaction or communication sequences.
Unlike the datalad-core test UI, this is not only provisioning
user input. In addition, it allows for inspecting a detailed UI
call log, and offers a text-rendering to easy debugging:
```
(Pdb) print(ui)
InteractiveTestUI(
question: (('attr1',), {'title': 'dummyquestion'})
response: attr1
question: (('attr2',), {'title': None})
response: attr2
question: (('secret',), {'title': None, 'repeat': True, 'hidden': True})
response: secret
(unused responses: [])
)
```
Closes #423
TODO
=> Replacement for `with_testsui`

datalad_next/archive_operations/tarfile.py, datalad_next/archive_operations/tests/test_tarfile.py, tools/appveyor/install-syspkgs
This PR adapts tararchive-operations to the recently updated type of `TarFileItem.name` to `PurePosixPath`.
=> Adapt tar-archive name type to type of `TarFileItem.name`, i.e. `PurePosixPath`

datalad_next/annexremotes/archivist.py
Fixes #439
Just a maintenance change removing an internal method in favor of an already existing generic helper of the ``SpecialRemote``.
=> Remove internal _getcfg() helper in favour of generic SpecialRemote helper

datalad_next/tests/fixtures.py
I noticed a few missing docstrings (``http_credential``, ``webdav_credential``), typos, and copy-paste errors (``http_server``) in the docstrings of these fixtures. Here is a quick fix.
Fixes #444
=> Add missing and fix wrong docstrings for HTTP/WebDAV server related fixtures

datalad_next/commands/tests/test_create_sibling_webdav.py, datalad_next/tests/utils.py
This fixes #32 with a simple extension to the ``check_common_workflow`` function for a recursive invocation of ``create-sibling-webdav``, a check for the appropriate number of results, and a check for the existence of the target directories of the recursively published subdataset.
I debated whether I should create a dedicated test to not inflate the ``check_common_workflow`` function, and I narrowly decided against it: By adding it to ``check_common_workflow`` the recursive mode gets tested for every ``mode`` automatically, and the increase in time is 1.5-2 seconds over the entire test suite. In comparison, a dedicated test function adds 3-4 seconds for just setting up the dataset hierarchy (see timings below). But I'm happy to do it in a dedicated test if others prefer that.
```
pytest …
```
=> Add a simple test for create-sibling-webdav's recursive mode

docs/CODEOWNERS
Adds christian.moench@web.de to the release team
This PR replaces PR #443 because the PR for branch of my fork did not get picked up by appveyor
=> Add christian.moench@web.de to release team

datalad_next/annexremotes/archivist.py, datalad_next/annexremotes/uncurl.py
This code removed here is merely a left-over for when this base class functionality did not exist yet.
=> Small cleanup for using existing base class helpers, when possible

changelog.d/20231003_111547_michael.hanke_bf_462.md, datalad_next/iter_collections/tests/test_utils.py, datalad_next/iter_collections/utils.py
=> `FileSystemItem.from_path()` now honors `link_target=False`

changelog.d/20231004_180525_mslw.md, datalad_next/commands/ls_file_collection.py
This PR will include `gitworktree` among the available file collection types listed in `ls-file-collection`'s docstring. Fixes #470 
The proposed docstring favours brevity, but does not cover nuances which could be included:
- `hash` being required for `size` to be reported
- reporting being based on `git ls-files --stage --cached --exclude-standard --others`
=> Add gitworktree to ls-file-collection's docstring

datalad_next/datasets/__init__.py, docs/source/conf.py
Explicitly list the few `call_annex()` methods we aim to support. Most others (`annex_records()` etc) are better covered by iterators.
=> More properly present docs on the repo classes

datalad_next/patches/enabled.py, datalad_next/patches/run.py, datalad_next/patches/tests/test_run.py, docs/source/patches.rst
This is the companion of https://github.com/datalad/datalad/pull/7509
Closes #478
=> Patch `run()` placeholder substitutions to honor configuration defaults

setup.cfg
This is the oldest Python version not EOL. Moreover, datalad-next happens to already rely on 3.8 API (e.g. `gzip.BadZipFile`).
Closes #481
=> Bumpy minimal Python dep to 3.8

datalad_next/datasets/__init__.py
This was prematurly done in
https://github.com/datalad/datalad-next/pull/479 without an actual need or application as a motivation.
The change is likely to come eventually, but should be approached in a less adhoc fashion.
This conincidentally avoids the minor version upgrade otherwise implied by #479.
=> Revert the API extension of `LeanAnnexRepo`

datalad_next/patches/run.py
Reported by @yarikoptic in
https://github.com/datalad/datalad/pull/7509/files#r1358426552
This changeset adds protection against processing non-substitution configuration items.
It also reduces duplication a bit more.
In contrast to the change proposal in
https://github.com/datalad/datalad/pull/7509 the (intermediate) set size is minimized by using a early filter.
=> Fix run substitution patch

changelog.d/20231023_064405_michael.hanke_www_auth.md, datalad_next/url_operations/http.py, datalad_next/utils/requests_auth.py, datalad_next/utils/tests/test_parse_www_authenticate.py, setup.cfg
Replace the www-authenticate dependency with internal function
The implementation is built on request's parsing utilities rather than elusive regexes. I find this better to grasp.
The associated test includes all www-authenticate test cases, plus a set of additional ones that focus on multi-challenge header specifications.
Closes #493
=> Replace www-authenticate

datalad_next/archive_operations/tests/test_tarfile.py, datalad_next/commands/tests/test_ls_file_collection.py, datalad_next/iter_collections/tests/test_itertar.py, datalad_next/patches/tests/test_annex_progress_logging.py, datalad_next/tests/fixtures.py, datalad_next/tests/marker.py, datalad_next/url_operations/tests/test_http.py
This is primarily achieved via a custom pytest mark. However, there is a session-level fixture that itself depends on network access. Unlike with a function-level fixture, I cannot figure out how to make any dependent test be skipped. Instead, I need to use the mark as a skipping decorator.
With these changes I can successfully run the test suite on a system with no network access (not just a proxy-based diversion):
```
247 passed, 39 skipped, 19 warnings in 171.10s (0:02:51)
```
Ping #490
=> Let the test battery honor DATALAD_TESTS_NONETWORK

.github/workflows/mypy.yml
The previous setup tried everything and produces an overwhelming report that nobody would pay attention to. This new approach would selectively report on content that is near that touch be a specific PR.
Closes #501
=> Type annotation check simplified and only scanning changes

changelog.d/20231025_202631_michael.hanke_bf_core_7522.md, datalad_next/patches/enabled.py, datalad_next/patches/update.py
Companion of https://github.com/datalad/datalad/pull/7522
Closes #506
=> Patch update for more robust behavior with adjusted branches

datalad_next/patches/cli_configoverrides.py, datalad_next/patches/commanderror.py, datalad_next/patches/create_sibling_gitlab.py, docs/source/developer_guide/index.rst, docs/source/index.rst, docs/source/patches.rst
Mostly listing all patches and removing some redundancies.
=> Documentation update

.github/workflows/mypy.yml
Make the report narrowly focused on the changeset of a PR. See comments inside for rational.
=> Tune type checker workflow

changelog.d/20231026_185357_michael.hanke_archivist_tgz.md, datalad_next/types/archivist.py, datalad_next/types/tests/test_archivist.py
This seems to be at least as sensible as `.tar`.
Closes #517
=> Support archive type detection for `.tgz` annex keys

datalad_next/url_operations/http.py, datalad_next/url_operations/tests/test_http.py
This PR adds a test to verify that http-download reports progress if no content-length is provided in the http-result headers. In addition the comments w.r.t. to download size calculation are updated to reflect the code.
This is a small add-on to #365 (which was already merged)
=> Add tests for progress report on size-less http downloads

datalad_next/iter_collections/tests/test_iterzip.py, datalad_next/iter_collections/zipfile.py
This PR keeps the seemingly neverending iterator item name story alive. 
The problem is that directory names in zip-archives possess a trailing '/'. We currently use `PurePosixPath` instances to represent file- and directory-entries in all types of collections. This leads to the necessity of special handling in ZipArchiveOperations, for example, when checking for containment (because `ZipFileItem.name` cannot be used directly):
```python
...
for item in iter_zip(...):
if (str(item.name) + '/' if item.type == FileSystemItemType.directory else item.name) in zip_archive:
...
``` 
Instead of the "canonical" way that is used in TarArchiveOperations:
```python
...
for item in iter_tar(...):
if item.name in tar_archive:
...
``` 
This PR adds the class `ZipFileDirPath`, which is a direct subclass …
=> Fix directory name handling in zip-iterator

.appveyor.yml
This should help to identify exceptionally slow tests that cause needless friction for iterations on PRs.
Outcome of the first set of reports (for datalad-next owned tests) at https://github.com/datalad/datalad-next/issues/522
=> Let pytest report the TOP20 of slowest tests

datalad_next/conftest.py, datalad_next/tests/fixtures.py
This is an attempt to denoise the test output.
~~There seems to be something special about git-fetch/push logging from datalad-core, but overall this is much better.~~
It removes about 1k lines from the CI run output, about ~25%.
Ping #503
=> Throw away INFO log messages in test runs

datalad_next/constraints/tests/test_compound.py
```
SyntaxWarning: "is" with a literal. Did you mean "=="?
```
Closes #526
=> Do not compare literal with `is`

datalad_next/annexremotes/tests/test_archivist.py, datalad_next/annexremotes/tests/test_uncurl.py, datalad_next/commands/tests/test_create_sibling_webdav.py, datalad_next/commands/tests/test_credentials.py, datalad_next/commands/tests/test_ls_file_collection.py, datalad_next/conftest.py, datalad_next/constraints/tests/test_cmdarg_validation.py, datalad_next/constraints/tests/test_tutorial.py, datalad_next/gitremotes/tests/test_datalad_annex.py, datalad_next/patches/tests/test_configuration.py, datalad_next/patches/tests/test_create_sibling_ghlike.py, datalad_next/patches/tests/test_run.py, datalad_next/tests/fixtures.py
The fixture is function-scope.
Edit: Test logs say this works. I should now extend it to the entire codebase.
=> New test fixture to disable DataLad command renderer

datalad_next/tests/utils.py
DAV server logs produce many lines of output during test runs that obscure more relevant messages.
This change makes the server logging conditional on a datalad log level of debug or more verbose.
Ping #503
=> Disable test DAV server logging by default

datalad_next/itertools/itemize.py, datalad_next/itertools/tests/test_itemize.py
This addresses an issues brought up in
https://github.com/datalad/datalad-next/pull/539#discussion_r1403427421
This changeset removes the default argument to avoid the impression that "line-processing" is the main target. The code does not imply that, and the existing usage also not.
The possibility to do line-splitting is not touched (or removed). The documentation needs no adjustment.
=> Remove default separator from `itemize()`

datalad_next/iter_collections/gitworktree.py
In #540 I found about ~10% of the runtime to be attributable to the regex-matching. This patch replaces the regex with two split() calls. In local benchmarks I see a ~10% speedup.
One major other source of slow-down was/is the construction of `PurePosixPath` objects. It seems this is being taken care of by https://github.com/python/cpython/issues/101362 and will be resolved eventually.
Closes #540
=> Replace regex approach to `ls-files` output parsing

datalad_next/itertools/itemize.py
=> Fix type annotations in `datalad_next/itertools/itemize.py`

datalad_next/iter_collections/gitworktree.py, datalad_next/iter_collections/tests/test_itergitworktree.py
This adds support for a standard query that Gooey would be making. Therefore, this is a significant step towards a resolution of https://github.com/datalad/datalad-next/issues/323.
When interfaced with https://github.com/datalad/datalad-next/pull/539, it replaces `gooey-lsdir` and half of `gooey-status-light`, with a much more efficient/convenient implementation.
Also:
- Closes #463 
- Closes #468 
- Closes #551
=> Add a mode and test for non-recursive `iter_gitworktree()`, plus fixes

datalad_next/commands/ls_file_collection.py, datalad_next/commands/tests/test_ls_file_collection.py, datalad_next/iter_collections/__init__.py, datalad_next/iter_collections/annexworktree.py, datalad_next/iter_collections/tests/test_iterannexworktree.py, datalad_next/itertools/__init__.py, datalad_next/itertools/load_json.py, datalad_next/itertools/reroute.py, datalad_next/itertools/tests/test_decode_bytes.py, datalad_next/itertools/tests/test_load_json.py, datalad_next/itertools/tests/test_reroute.py
This is moving PR https://github.com/mih/datalad-next/pull/3 here, to get it tested properly. Below is the original description by @christian-monch 
It includes (sits on top of) https://github.com/datalad/datalad-next/pull/538 (merged now)
TODO
----
This PR adds an implementation of `iter_annexworktree` that is based on `iterable_subprocesses` and the ideas laid out in issue https://github.com/datalad/datalad-next/issues/537.
This PR included a collection of data processors that are basically generator-wrapper.
The PR also modifies `iter_gitworktree` to use `iterable_subprocesses` instead of the datalad-core runner.
The current implementation of `iter_annexworktree` iterates over a dataset with 33k annex files in less than 5 seconds on my machine.
=> `iterable_subprocess` based `annexworktree()`

setup.cfg
For now, we only need a single iterator from it. However, with the switch to `iter_subproc()`, more usage is to be anticipated.
For testing this is not actually a new dependency. `cheroot` already pulled it in.
Closes #556
=> Add `more_itertools` as a dependency

datalad_next/iter_collections/annexworktree.py
This commit fixes issue #559.
It allows `itemize` to any of multiple line-separators to separate the output of `git annex find`. This takes care of the fact that some git-annex versions will output an unrequested `'\r'` in addition to a requested `'\n'`.
=> fix issue #559, a Windows line endings-related bug

datalad_next/iterable_subprocess/iterable_subprocess.py, datalad_next/iterable_subprocess/test_iterable_subprocess.py, datalad_next/runners/iter_subproc.py
This PR implements a solution for the problem of not-easily available return codes that was discussed [here](https://github.com/datalad/datalad-next/pull/546#discussion_r1418976060) in PR #546.
This is an alternative (and in my view superior) approach to the discussed solution, which is implemented in PR #562.
The reason why this second approach exists is:
1. It seems much more pythonic to me
2. It is more general and does not introduce special handling of different exceptions (in this case, the handling of `StopIteration`in PR #562)
3. It makes for cleaner code when using `iter_subproc`, i.e. in `SshUrlOperations`.
=> Use `OutputFrom` class as `iter_subproc` result, which keeps returncodes on exception

datalad_next/itertools/__init__.py, datalad_next/itertools/align_pattern.py, datalad_next/itertools/tests/test_align_pattern.py, datalad_next/runners/__init__.py, datalad_next/runners/iter_subproc.py, datalad_next/url_operations/__init__.py, datalad_next/url_operations/ssh.py, datalad_next/url_operations/tests/test_ssh.py
This is nothing, but a linearized variant of the exact same diff as #566, with commits rechunked to reflect changes of the mainline, rather than an internal evolution of the PR.
This PR removes the last use of `ThreadedRunner` from the code base.
=> Use `iter_subproc` instead of `ThreadedRunner` in `SshUrlOperations`

datalad_next/constraints/git.py
This is a step towards #541. While we may want to have an abstraction layer for such simple calls, there is no point in keeping the heavy `GitRunner` here.
Possible a trivial wrapper around `subprocess.run()`, further triming the space of possibilities would be useful.
But this PR is not the space for a big-picture change.
=> Replace `GitRunner` usage with plain `subprocess`

datalad_next/annexremotes/tests/test_uncurl.py, datalad_next/constraints/tests/test_cmdarg_validation.py, datalad_next/constraints/tests/test_compound.py, datalad_next/gitremotes/datalad_annex.py, datalad_next/gitremotes/tests/test_datalad_annex.py
=> Import constants from new/dedicated location (not utils)

datalad_next/iter_collections/annexworktree.py, datalad_next/iter_collections/gitworktree.py, datalad_next/iterable_subprocess/iterable_subprocess.py, datalad_next/runners/iter_subproc.py, datalad_next/runners/tests/test_iter_subproc.py
Running in a particular working directory is a very common paradigm (think in a Git repository). So far, we used Git's `-C` option to perform the directory changes. This is fine, fast, and works universally.
However, recent discussion asked whether it would make sense to call annex commands via `git-annex`, rather than `git annex`. The former does not provide `-C`. This change readies the code for such a move.
Another use case for this is the passing of (many) file paths. With an option to run in a particular directory, the file names can be just that (not full paths). This can help to mitigate situations, where many file paths potentially exhaust the max command length.
=> Enhance `iter_subproc` with a `cwd` parameter

datalad_next/commands/create_sibling_webdav.py, datalad_next/commands/tests/test_create_sibling_webdav.py, datalad_next/constraints/__init__.py, datalad_next/constraints/git.py, datalad_next/constraints/tests/test_special_purpose.py
This is the streamlined version of #324 
Closes #193
=> `EnsureRemoteName` and uplift parameter validation in `create-sibling-webdav`

datalad_next/archive_operations/__init__.py, datalad_next/archive_operations/tests/test_zipfile.py, datalad_next/archive_operations/zipfile.py, datalad_next/conftest.py
This changeset an implementation `ArchiveOperations` for ZIP files. It makes use of `datalad_next.iter_collections.zipfile.iter_zip` to implement iteration.
The tests include a pytest-fixture called `structured_sample_zip`, which reports on a sample ZIP from the `sample_zip` fuxture, with its properties readily accessible. It should likely replace `sample_zip`.
Replaces #407
=> Add `ZipArchiveOperations` with tests

datalad_next/iter_collections/annexworktree.py, datalad_next/iter_collections/gittree.py, datalad_next/iter_collections/gitworktree.py, datalad_next/runners/__init__.py, datalad_next/runners/iter_subproc.py
This is a thin wrapper around `iter_subproc` that is to be used unconditionally whenever the command given to `iter_subproc` would start with `git`.
Presently, this wrapper does nothing but adding that `'git'` argument to the front of any argument list.
Eventually, it might be used to call a configurable Git binary, establish certain environment conditions for all Git calls, etc.
Right now, this is just cheap future-proofing.
Closes #584
=> Common helper to call Git subprocesses

datalad_next/commands/ls_file_collection.py, datalad_next/commands/tests/test_ls_file_collection.py, datalad_next/iter_collections/annexworktree.py, datalad_next/iter_collections/directory.py, datalad_next/iter_collections/gittree.py, datalad_next/iter_collections/gitworktree.py, datalad_next/iter_collections/tarfile.py, datalad_next/iter_collections/tests/test_itergittree.py, datalad_next/iter_collections/tests/test_itertar.py, datalad_next/iter_collections/tests/test_iterzip.py, datalad_next/iter_collections/utils.py, datalad_next/iter_collections/zipfile.py
Previously, the `name` attribute was some kind of `PurePath` instance. The precise nature varied across item types and corresponding iterators.
This led to two problems:
- Performance (see #581): the creation of a Path instance is not particularly cheap. If a consumer does not need such an instance, and unconditional creation is a waste of resources
- Abstraction (see #430): the Path representation of a path-like name does not always match the exact semantics of the original name (it might have a trailing slash that has a purpose, etc)
Both problems are now addressed by relaxing the type of `.name` of a `PathBasedItem`. It can now be anything. Consumers that require an actual Path instance can use the `.path` attribute. An analog access is also implemented for `.link_target` (which now …
=> Change semantics of `PathBasedItem` names

datalad_next/iter_collections/__init__.py, datalad_next/iter_collections/gitdiff.py, datalad_next/iter_collections/tests/test_itergitdiff.py
This is a step towards https://github.com/datalad/datalad-next/issues/586 -- it implements comparison of Git tree-ishes with each other, or with *tracked* content in the worktree (ie., so support for untracked content).
Noteworthy items:
- includes test to verify that it does not suffer from https://github.com/datalad/datalad/issues/6791
- support for finding copies and renames (useful for https://github.com/datalad/datalad/issues/2160)
- uses `prev_gittype` for deletions (addresses https://github.com/datalad/datalad/issues/6877)
Performance notes
Comparing with `status` from datalad-core, on the studyforrest superdataset (11 subdatasets, ~4k files):
```
In [4]: %timeit status('.', result_renderer='disabled', untracked='no', recursive=True)
368 ms ± 10 ms per loop (mean ± std. dev. of 7 …
```
=> New `iter_gitdiff`

datalad_next/annexremotes/tests/test_uncurl.py, datalad_next/commands/tests/test_tree.py, datalad_next/gitremotes/tests/test_datalad_annex.py, datalad_next/tests/utils.py
There were a handful of tests reported in #525 that failed when ran as root. This PR implements the proposed solution to skip these tests when ran as root, using a preexisting pytest util from datalad-core.
fixes #525
=> Skip tests when ran as root

datalad_next/__init__.py, datalad_next/commands/__init__.py, datalad_next/commands/results.py, datalad_next/commands/status.py, datalad_next/commands/tests/test_results.py, datalad_next/commands/tests/test_status.py, datalad_next/constraints/base.py, datalad_next/constraints/git.py, datalad_next/iter_collections/annexworktree.py, datalad_next/iter_collections/gitdiff.py, datalad_next/iter_collections/gitstatus.py, datalad_next/iter_collections/gitworktree.py, datalad_next/iter_collections/tests/test_itergitdiff.py, datalad_next/iter_collections/tests/test_itergitstatus.py, datalad_next/repo_utils/__init__.py, datalad_next/repo_utils/tests/test_head.py, datalad_next/runners/__init__.py, datalad_next/runners/git.py, datalad_next/runners/iter_subproc.py, datalad_next/runners/tests/test_git.py, docs/source/api.rst, docs/source/cmd.rst
[Although this PR is big, it does not break API (only additions). The only "breaking" change is a relocation of `iter_git_subproc()`, which was never released so far.]
- Closes #323
- Closes #418
- Closes #586
- Closes #597
It can eventually replace `datalad status`.
Feature and differences of this new implementation (compared to datalad-core):
- Does not use any of the datalad-core tooling for diffing (`Repo.diffstatus`, etc.)
- all generator-based implementation
- command results are `dataclass` now, no longer result-dict -- first of this kind
- more closely aligned with Git, for example, no listings, just change reports
- capable of reporting modification types for container items (submodules, directories): new commits, modified/untracked content
- proper typechange detection
- strict …
=> Initial draft of `iter_gitstatus()` and `datalad next-status`

datalad_next/iter_collections/annexworktree.py, datalad_next/iter_collections/gitworktree.py, datalad_next/iter_collections/tests/test_iterannexworktree.py, datalad_next/iter_collections/tests/test_itergitworktree.py
When reporting file pointers. Both stumbled over files that were still reported by `ls-file`, but did not exist on the filesystem anymore (this happens when a deletion is not committed/staged).
This change makes both iterators fall back on yielding a non-filesystem work tree item in this case.
The corresponding tests have been adjusted to cause and adapt to this case.
Closes #582
=> Make `iter_git|annexworktree()` robust to deleted files

datalad_next/url_operations/tests/test_any.py
=> Fix invalid escape sequence

datalad_next/iter_collections/gitstatus.py
This can dramatically boost performance with many submodules. Checking
the filesystem for a file is much cheaper than running `git rev-parse`.
When a subdataset is present, this obviously means an additional cost.
However, in comparison to the then following state evaluation, it should
still be cheap.
Worth it, IMHO.
Closes: #606
=> Introduce early check for submodule presence in status evaluation

datalad_next/utils/__init__.py, datalad_next/utils/tests/test_deprecated.py, datalad_next/utils/tests/test_paramdictator.py
Fixes #609
Adds a regression test for `datalad_next.utils.ParamDictator`.
=> Fix `datalad_next.utils.ParamDictator`

datalad_next/iterable_subprocess/test_iterable_subprocess.py
This PR modifies the test `datalad_next.iterable_subprocess.test_iterable_subprocess.test_success_returncode_available_from_generator_with_exception` to simply check for a non-`None` return code instead of checking for a `0` return code.
The reason is that a `StopIteration`-exception that occurs before the subprocess has terminated might lead to a non-`0` return code, thus failing the test. Some environments might trigger such an early exception, e.g. due to some unexpected stdout-configuration. In other words, we cannot guarantee a `0` return code in all environments. But we can guarantee, that a return code is available when the `iterable_subprocess`-context is exited with an exception.
The test is renamed to `test_returncode_available_from_generator_with_exception`.
This should make …
=> Robustify tests of `iterable_subprocess`

datalad_next/annexremotes/archivist.py, datalad_next/types/__init__.py
See https://github.com/datalad/datalad-next/issues/613
=> Define public API of `datalad_next.types`

datalad_next/archive_operations/tarfile.py, datalad_next/archive_operations/tests/test_tarfile.py, datalad_next/archive_operations/tests/test_zipfile.py, datalad_next/archive_operations/zipfile.py, datalad_next/commands/ls_file_collection.py, datalad_next/commands/status.py, datalad_next/iter_collections/__init__.py
See https://github.com/datalad/datalad-next/issues/613
Quite a few candidates to move to `datalad_next.types` have been identified.
=> Define public API of `datalad_next.iter_collections`

datalad_next/annexbackends/tests/test_base.py, datalad_next/annexremotes/tests/test_archivist.py, datalad_next/annexremotes/tests/test_uncurl.py, datalad_next/commands/tests/test_create_sibling_webdav.py, datalad_next/commands/tests/test_credentials.py, datalad_next/commands/tests/test_download.py, datalad_next/commands/tests/test_ls_file_collection.py, datalad_next/commands/tests/test_status.py, datalad_next/commands/tests/test_tree.py, datalad_next/credman/tests/test_credman.py, datalad_next/gitremotes/tests/test_datalad_annex.py, datalad_next/iter_collections/tests/test_iterdir.py, datalad_next/iter_collections/tests/test_itergitdiff.py, datalad_next/iter_collections/tests/test_itergittree.py, datalad_next/iter_collections/tests/test_itergitworktree.py, datalad_next/iter_collections/tests/test_itertar.py, datalad_next/iter_collections/tests/test_utils.py, datalad_next/patches/tests/test_cli_configoverrides.py, datalad_next/patches/tests/test_configuration.py, datalad_next/patches/tests/test_push.py, datalad_next/patches/tests/test_push_to_export_remote.py, datalad_next/patches/tests/test_run.py, datalad_next/tests/__init__.py, datalad_next/tests/fixtures.py, datalad_next/tests/utils.py, datalad_next/url_operations/tests/test_http.py, datalad_next/url_operations/tests/test_ssh.py, docs/source/pyutils.rst
This pretty much takes the role of `datalad_next.tests.utils`. The new setup treats `tests` like any other sub-package and exposes reusable tools as a public API at the top-level.
In doing so, `SkipTest` was made obsolete and excluded from that API.
The usage of `rmtree` is altered to import from `datalad_next.utils`.
https://github.com/datalad/datalad-next/issues/613
=> Define public API of `datalad_next.tests`

datalad_next/annexremotes/tests/test_archivist.py, datalad_next/commands/credentials.py, datalad_next/credman/__init__.py, datalad_next/iterable_subprocess/__init__.py, datalad_next/runners/iter_subproc.py, docs/source/pyutils.rst
This PR lumps together a few smaller changes in this direction.
=> Define public APIs

datalad_next/config/__init__.py, datalad_next/consts/__init__.py, datalad_next/datasets/__init__.py, datalad_next/datasets/annexrepo.py, datalad_next/exceptions/__init__.py, datalad_next/runners/__init__.py, datalad_next/uis/__init__.py, datalad_next/utils/__init__.py, datalad_next/utils/specialremote.py, docs/source/conf.py, docs/source/index.rst
This continues the work done for #613. Now all relevant symbols are directly documented, for every top-level package.
In doing so, I added a first set of markers to shape the API streamlining that will come with v2.0.
Ping #624
Ping #616
Some implementations that continued to be located in `__init__.py` files have been move into new, dedicated source files.
=> Uplift Python API docs

datalad_next/commands/tree.py, datalad_next/iter_collections/__init__.py, datalad_next/iter_collections/gitstatus.py, datalad_next/iter_collections/gitworktree.py, datalad_next/repo_utils/__init__.py, datalad_next/repo_utils/worktree.py, docs/source/pyutils.rst
The previous implementation could now be made simpler, with fewer dependencies, using the new iterators. Here `iter_submodules()`.
This use case also helped to identify suboptimal code organization. See individual commits.
=> Free `tree` command from `subdatasets` dependency

datalad_next/gitremotes/datalad_annex.py, datalad_next/runners/git.py, datalad_next/utils/__init__.py, datalad_next/utils/patch.py, datalad_next/utils/tests/test_patch.py
Elevates the `call_git..()` helpers to have enough functionality to replace the observed usage patterns for `GitRepo.call_git..()` and other `Repo` centric runner call pattern.
All these are replaced with `call_git..()` utility from `datalad-next`.
Closes #541
=> Discontinue usage of `Runner` functionality for Git calls

datalad_next/commands/create_sibling_webdav.py, datalad_next/gitremotes/datalad_annex.py, datalad_next/gitremotes/tests/test_datalad_annex.py, datalad_next/patches/push_to_export_remote.py, datalad_next/tests/fixtures.py, datalad_next/utils/__init__.py, datalad_next/utils/patch.py, datalad_next/utils/tests/test_patch.py
This new helper has been lifted from #632, where is it used to do lean patching of subprocess ENVs. However, it is generally useful.
We should not need to import `unittest` for normal operations.
=> Consolidate ENV patching on dedicated `patched_env()` helper

datalad_next/gitremotes/datalad_annex.py, datalad_next/patches/push_optimize.py
The `mirrorrepo` property of the datalad-annex Git remote helper implementation creates an empty repository, if the remote has no refs (or does not exist). This is sensible behavior for enabling initial pushes.
However, it leads to successful but empty clones/fetches for any misspecified URL or connectivity failure. This is undesirable.
This change adds an explicit test for an available/accessible repository deposit, whenever a clone/fetch is performed. Wrong URL specifications or connectivity issues will now lead to an explicit error exit. This fact is communicated via a non-verbose message, and the full error is available at verbosity level 2, i.e. with a `git clone -v`.
- Closes: https://github.com/datalad/datalad-next/issues/636
TODO
=> `datalad-annex::` Test for a repository deposit before establishing mirrorrepo 

changelog.d/20240407_154322_michael.hanke_bf_639.md, datalad_next/iter_collections/gitdiff.py
With this change, a dedicate `update-index` refresh run is performed before running `diff-index`. This fixes undesired modification reports that are triggered by mtime-change only.
This comes at a performance cost. For a repo with 36k files (many-ish), this is about 5% of the total runtime:
```
%timeit next_status('.', result_renderer='disabled', untracked='all', recursive='datasets')
229 ms ± 537 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
%timeit next_status('.', result_renderer='disabled', untracked='all', recursive='datasets')
240 ms ± 2.59 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Closes #639
=> Make `iter_diff()` robust to lstat-only changes

.coveragerc, datalad_next/iterable_subprocess/iterable_subprocess.py, datalad_next/itertools/align_pattern.py, datalad_next/itertools/tests/test_align_pattern.py, datalad_next/runners/iter_subproc.py, datalad_next/shell/__init__.py, datalad_next/shell/operations/common.py, datalad_next/shell/operations/posix.py, datalad_next/shell/response_generators.py, datalad_next/shell/shell.py, datalad_next/shell/tests/test_response_generators.py, datalad_next/shell/tests/test_shell.py, datalad_next/tests/utils.py, docs/source/conf.py, docs/source/pyutils.rst
This PR addresses issue #572 
It provides a `shell_connection`-context manager that will start a shell, for example, a local ssh-client, and allows interaction with the shell-process. Interactions are started by sending a command, which will be executed in the shell. The user will then receive the command's `stdout`. When the command terminates, the user can retrieve the exit code of the command.
Usage example:
```python
>>> from datalad_next.shell import shell
>>> with shell(['ssh', 'localhost']) as ssh:
...     r = ssh(b'ls -l /etc/passwd')
...     print(tuple(r))
...     print(r.returncode)
... 
(b'-rw-r--r-- 1 root root 2773 14. Nov 10:05 /etc/passwd\n',)
0
```
=> Add `PersistentSubShell`-feature

datalad_next/shell/tests/test_shell.py
This commit fixes the test
`test_fixed_length_response_generator_powershell`, which fails on certain PowerShell-versions. The test is skipped on those versions.
Closes https://github.com/datalad/datalad-next/issues/662
=> Fix a test that fails due to a PowerShell bug

.github/workflows/codespell.yml, .github/workflows/docbuild.yml, .github/workflows/mypy.yml, .github/workflows/update-contributors.yml
This updates the following GitHub actions:
- `actions/checkout` v4 → v5 and `actions/setup-python` v4 → v5, to address warnings (Node.js 16 actions are deprecated) in GitHub which show up in workflow runs
- `tj-actions/changed-files` v23 → v44, to address other warnings which show up in GitHub workflow runs
- `vsoch/pull-request-action` v1.0.24 → v1.1.1 to address workflow ending with an error
=> Update versions of GitHub actions

.appveyor.yml
Test size started to outgrow it. Eventually, we want to look at what is consuming all that space and start cleaning things up better.
Closes: https://github.com/datalad/datalad-next/issues/674
=> Increase FS for crippled test runs to 750MB

changelog.d/20240426_082448_michael.hanke_bf_670.md, datalad_next/iter_collections/annexworktree.py, datalad_next/iter_collections/tests/test_iterannexworktree.py, datalad_next/repo_utils/__init__.py, datalad_next/repo_utils/annex.py, datalad_next/repo_utils/tests/test_annex.py
This fixes an obscure
`iterable did not yield matching item for route-in item, cardinality mismatch?`
error when attempting such a query before.
This fix is a choice. An alternative could be to error out in this case. I went for this approach, because the test is cheap, and not much more expensive than catching the previous error in a precise manner.
With this change, the items of the underlying `gitworktree` iterator are yielded, after funneling them through the `annexworktree` iteration post-processing to ensure type-alignment and other (future) side-effect. The outcome is therefore identical to items in Git yielded from an annex-enabled repository.
Closes: https://github.com/datalad/datalad-next/issues/670
TODO:
=> Enable running `iter_annexworktree()` on just-Git repos

changelog.d/20240507_190704_michael.hanke_bf_637.md, datalad_next/commands/status.py, datalad_next/iter_collections/gitdiff.py, datalad_next/iter_collections/gitstatus.py, datalad_next/iter_collections/tests/test_itergitstatus.py, datalad_next/tests/fixtures.py
TODO:
- Closes #637 
- Closes #640 
- Closes #645
Screenshot on the default output of `next-status -r mono`, arrows highly the changes.
=> Elevate `next-status` and `iter_gitstatus()`

changelog.d/20240514_071318_michael.hanke_bf_680.md, datalad_next/iter_collections/gitstatus.py, datalad_next/iter_collections/tests/test_itergitstatus.py, datalad_next/repo_utils/worktree.py
Previously, the implementation would only report on untracked content in work trees of repositories with no HEAD commit. This led to staged changes not being reported.
The new implementation detects a no-HEAD situation and compares to the PRE_INIT_COMMIT_SHA.
A test is added.
Closes #680
=> Fix no-HEAD handling in `iter_gitstatus()`

datalad_next/config/utils.py
This violates the promises made in the type annotation of this function. However, it is necessary (at least for now) in order to regain compatibility with an (anti-)feature of the DataLad CLI.
The underlying issue is documented in
https://github.com/datalad/datalad/issues/7589
TL;DR: DataLad promises to be able to unset a git config item -- but this is not supported by Git, and also DataLad can only achieve this within a single, top-level process.
With this commit `None` value (e.g. coming from the CLI) is treated as an empty string. It also ensures that all values are strings instead of, for example,
`int`.
It adds a paragraph to the doc-string of
`datalad_next.config.utils.set_gitconfig_items_in_env` to document its behavior if a configuration item
has a `None`-value.
This isssue has …
=> `set_gitconfig_items_in_env()`: treat `None` as empty string

.codespell-exclude, .github/workflows/codespell.yml, changelog.d/20240514_212532_michael.hanke_patch_create_sibling_ria.md, datalad_next/config/utils.py, datalad_next/patches/add_method_url2transport_path.py, datalad_next/patches/customremotes_main.py, datalad_next/patches/enabled.py, datalad_next/patches/fix_ria_ora_tests.py, datalad_next/patches/patch_ria_ora.py, datalad_next/patches/replace_create_sibling_ria.py, datalad_next/patches/replace_ora_remote.py, datalad_next/patches/replace_sshremoteio.py, datalad_next/patches/ria_utils.py, datalad_next/patches/tests/test_add_method_url2transport_path.py, datalad_next/patches/tests/test_replace_ora_remote.py, datalad_next/patches/tests/test_ria.py, docs/source/patches.rst
This PR addresses the issues with Windows-clients that use RIA-stores. It replaces the classes `datalad.distributed.ora_remote.ORARemote` and `datalad.distributed.create_sibling_ria.CreateSiblingRia` with updated versions that should work properly on Linux, OSX, and Windows.
The main difference to the original code is that all path-operations, e.g. to determine the location of `ria-layout-version`, are performed on URL-paths. Those are represented by instances of `PurePosixPath`. All subclasses of `BaseIO`, i.e. `LocalIO`, `SSHRemoteIO`, and `HTTPRemoteIO`, are extended to contain the method `url2transport_path`. This method converts an URL-path into the correct path for the respective IO abstraction.
Before methods on a subclass of `BaseIO` that require a path are called, the generic …
=> Patch RIA and ORA code to work on multiple client platforms

datalad_next/shell/operations/posix.py, datalad_next/shell/shell.py, datalad_next/shell/tests/test_shell.py
Fixes issue #661 
This PR automatically quotes all path parameters provided as `Path` or `PurePosixPath`-instances to `shell.posix`-functions via `shlex.quote`.
Byte-parameter like the `command`-parameter of `ShellCommandExecutor.__call__()` are never quoted. The caller has to ensure that file names are properly quoted. The are a number of reasons for this policy:
1. It is not clear which syntax is used by the shell-program, for example, it could be: `bash`, `PowerShell`, `Python`, etc.
2. Even if the shell-program was known, e.g. `bash`, there is no way to generally determine whether a path is contained in the command-argument.
=> Consistent shell command quoting

datalad_next/archive_operations/tests/test_tarfile.py, datalad_next/archive_operations/tests/test_zipfile.py
Discovered by Debian maintainer.
- Closes #691 
This patch is part of Debian's 1.4.0-1
=> Rename test helper class to avoid confusion with test class

pyproject.toml
Tests are executed with `pytest --strict-marker` now to catch undesired situations due to mistyped markers. DataLad (core) implements many of its old test decorators as markers, but does not declare them. This change add a missing one.
Refs: https://github.com/datalad/datalad-next/pull/692
=> test(markers): add missing datalad-core marker "integration"

datalad_next/tests/utils.py, pyproject.toml
Discovered by Debian maintainer.
This patch is part of Debian's 1.4.0-1
=> Add missing import (for non-WebDAV fallback)

datalad_next/patches/patch_ria_ora.py
Since 1.4.0 a plain `datalad_next` import required `pytest`. This was due to the datalad-core patch `fix_ria_ora_tests` added in #669, and was discovered by Debian's CI
Thanks to @aqw for the recommendation.
Closes: https://github.com/datalad/datalad-next/issues/698
Refs: https://github.com/datalad/datalad-next/pull/669, https://ci.debian.net/packages/d/datalad-next/testing/amd64/46884776/
=> fix(dependencies): limit test patch import to test runs

datalad_next/patches/add_method_url2transport_path.py, datalad_next/patches/replace_ora_remote.py, datalad_next/patches/ria_utils.py
The patched code is new patch-code, introduced in
https://github.com/datalad/datalad-next/pull/669
The assertions were added to make sure that no platform paths are passed around. The Debian maintainer observed non-pure paths coming in. This may need an investigation, but this changeset maintains the spirit of the assertions while relaxing them enough to let the tests pass in a Debian build environment.
Ping @christian-monch WDYT?
This patch is part of Debian's 1.4.0-1
=> Relax type assertion from PurePosixPath to PosixPath in RIA patches

CHANGELOG.md, README.md, datalad_next/iter_collections/gitstatus.py
It relies on `rev-parse --path-format=relative`, which has been added in 2.31.
Thanks to @FeHoff for reporting!
Closes: https://github.com/datalad/datalad-next/issues/702
=> docs: add note of Git >= v2.31 requirement for next-status

.changelog.md.j2, CHANGELOG.md, pyproject.toml
Changelog generated via `cz bump --changelog`
Applied manual edits afterwards, and redid tag.
=> Custom changelog

CHANGELOG.md
This increases the focus on GitHub, but any renderer of a commit would work. If we post this to radicle, we could have a completely non-central resolver.
=> style(changelog): more convenience with a direct commit link

datalad_next/gitpathspec/__init__.py, datalad_next/gitpathspec/pathspec.py, datalad_next/gitpathspec/pathspecs.py, datalad_next/gitpathspec/tests/test_gitpathspec.py, datalad_next/iter_collections/gitstatus.py, datalad_next/iter_collections/gitworktree.py, datalad_next/iter_collections/tests/test_itergitstatus.py, datalad_next/iter_collections/tests/test_itergitworktree.py, docs/source/pyutils.rst
This is yet another attempt towards pathspecs. It replaces #714 with something even more low-level and lightweight.
- Closes: #587
TODO
=> Git pathspecs and submodule recursion for `iter_gitworkstree()` with pathspec support

datalad_next/constraints/git.py
There should be no functional change, just `assert` statements in strategic places that help `mypy` infer that things are correct the way they are.
=> rf(EnsureRemoteName): satisfy type-annotation checker

.changelog.md.j2
Compared to the previous setup, this support auto-compaction of item with the same scope identifier.
=> style(changelog): adopt changelog template from `datasalad`

datalad_next/iter_collections/gitstatus.py, datalad_next/iter_collections/tests/test_itergitstatus.py
This are new containers. The previous implementation only expected modification of containers, not new submodule container directly, and crashed.
This change adds support for this case and a test that verifies it.
=> fix(iter_gitstatus): support newly added submodules

datalad_next/itertools/tests/test_align_pattern.py
This PR deletes the test `datalad_next.itertools.tests.test_align_pattern.test_performance`, which did not assert any properties, but just printed some performance measurements.
=> Remove non-asserting test from align_pattern tests

datalad_next/annexremotes/uncurl.py
This PR adds a close-handler to the uncurl annex remote. The handler closes all open `url_operations-instances`. This allows, for example, to terminate all `shell`-related threads and to exit the uncurl-process.
=> Add a `close`-handler to the uncurl-annex remote

.appveyor.yml
This PR disables the test `datalad.locals.tests.test_wtf.test_wtf`. The test fails due to an error in datalad's test code and leads to failing `datalad-next`-CI runs.
A fix has been proposed in datalad, see
[issue datalad #7627](https://github.com/datalad/datalad/issues/7627) and the corresponding [PR datalad #7628](https://github.com/datalad/datalad/pull/7628).
Once [PR datalad #7628](https://github.com/datalad/datalad/pull/7628) is merged the commit in this PR can be reverted.
=> Test: disable `datalad.locals.test.test_wtf.test_wtf`

datalad_next/patches/enabled.py, datalad_next/patches/interface_base.py, docs/source/patches.rst
This is achieved by a new patch, because the behavior is caused by datalad-core's tooling.
The approach taken is to delete memory address statements like '... at 0x...', and delete them via a regex -- similar to what sphinx is doing for documentation generation.
The patch is not similar to sphinx, but global, because memory addresses also have little to no utility for runtime documentation too.
This actually affects only a single usage of a function pointer used as a default argument.
Closes: https://github.com/datalad/datalad-next/issues/709
=> doc: exclude memory addresses from documentation

datalad_next/url_operations/base.py, datalad_next/url_operations/file.py, datalad_next/url_operations/ssh.py, datalad_next/url_operations/tests/test_file.py, datalad_next/url_operations/tests/test_ssh.py
This PR addresses issue [datalad-ria #102](https://github.com/datalad/datalad-ria/issues/102) and touches on issue #454 where atomic upload operations are discussed as well.
The PR also adds atomic upload to files. This can prevent data loss in the case where multiple threads write to the same file concurrently.
All ssh- and file-uploads should be atomic, which means an `atomic`-parameter that controls atomicity on a per-call basis is not necessary.
=> Atomic UrlOperations.upload for ssh- and file-URLs 

datalad_next/iter_collections/gitworktree.py
`decode_bytes()` can yield multiple output chunks for one input chunk (in the case of decoding errors). This implies that it cannot be meaningfully used after `itemize()` without threatening the semantics of the items (i.e., with split-by-line items are no longer unique lines).
For this reason, this commit changes the order of these helpers in the `gitworktree()` implementation.
Refs: https://github.com/datalad/datalad-next/issues/740
=> fix(`gitworktree`): decode bytes before itemization

datalad_next/itertools/decode_bytes.py, datalad_next/itertools/tests/test_decode_bytes.py
The previous implementation enabled error handling in decoding only for the segment of a bytestring that an exception was raised for.
However, it may well be that more decoding errors exist in other parts of the bytestring. I have a complicated real-world case where this happens, i.e. raising `UnicodeDecodeError` again, even though `decode_bytes` was called with `backslash_replace=True`.  Unfortunately the data is so large that I did not manage to catch the condition exactly.
It seems to be a needless sophistication to decode some part of the bytestring with error handling, but not another.
There is a good chance that this patch is badly interacting with the logic to obtain the next chunk before attempting a decoding again.
=> fix(`decode_bytes`): always backslashreplace when asked to

datalad_next/itertools/decode_bytes.py, datalad_next/itertools/tests/test_decode_bytes.py
The contained new test documents how error handling in `decode_bytes()` caused data in a subsequent chunk to be skipped. The reason for that was that the pointer variable was not reset when a chunk (or rather the joined data of any previous chunks) was fully decoded. Decoding in the next chunk would start from the position last recorded during error handling in a previous chunk.
=> fix(`decode_bytes`): error handling led to data loss in subsequent chunks

datalad_next/iter_collections/gitdiff.py, datalad_next/iter_collections/gitstatus.py, datalad_next/iter_collections/tests/test_itergitdiff.py
Towards https://github.com/datalad/datalad-next/issues/598
=> Add support for pathspecs to `iter_gitdiff()`

datalad_next/patches/replace_create_sibling_ria.py
This PR fixes a bug where the canonified ria-store URL was assigned to `push_url` instead of the
canonified ria-store **push-URL**.
=> Fix `CreateSiblingRia` code in `replace_create_sibling_ria.py`

.appveyor.yml
With datalad release 1.1.1 `test_wtf` will pass and no longer let CI fail.
=> Fix tests: bring back datalad core wtf-test

docs/source/conf.py
I saw a deprecation warning in a recent doc build (https://github.com/datalad/datalad-next/actions/runs/10028357984/job/27715183098), but did not find the intersphinx mapping that was complained about anymore, so I assume it was removed. Thus, as far as I can see, this extension isn't used anymore
=> docs: remove unused intersphinx extension

datalad_next/__init__.py
At least the version import is an urgently needed fix.
=> Fix and update init

docs/source/_templates/autosummary/module.rst
Previously, the setup was confusing. Every symbol imported to module level was documented directly. If a ToC was added, sphinx would fail due to documentation generated twice for the same symbol.
The new setup **requires** a dedicated autosummary selection of documented content.
I think this is better. Often modules provide a lot of stuff, and direct documentation rendering on a single page is overwhelming. The explicit selection also allows for items to be excluded that are only there for technical or historical reasons. This allows for an overall more accessible documentation.
=> doc: trim module API documentation to an overview table of content

pyproject.toml
The project.urls are picked up and displayed (with matching icons, if
possible) by pypi.org. DataLad-next has its online documentation under
docs.datalad.org and it is pretty good. Given that we already include
a GitHub link in project.urls anyway (twice, in fact), it could be
better to point Documentation to the online docs, rather than the
GitHub README.
What do you think?
Side note: I would even be tempted to remove the Homepage link and
only keep Source (currently they are the same and point to the GitHub
project), but I wasn't sure if the Homepage is considered necessary or
not, and hence didn't include it in the original proposal.
=> Include a link to documentation page in project URLs

datalad_next/commands/tests/test_tree.py
https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve says:
_Changed in version 3.13:_ Symlink loops are treated like other
errors: `OSError` is raised in strict mode, and no exception is raised
in non-strict mode. In previous versions, `RuntimeError` is raised no
matter the value of _strict_.
Adjust a test to take account of this.
=> test: fix test_tree_with_broken_symlinks on Python 3.13
