.appveyor.yml, .coveragerc, .github/workflows/test_crippledfs.yml, README.md, datalad_next/backend/base.py, datalad_next/backend/tests/test_base.py, datalad_next/backend/xdlra.py, datalad_next/credman.py, datalad_next/gitremote/datalad_annex.py, datalad_next/gitremote/tests/test_datalad_annex.py, datalad_next/tests/utils.py, docs/source/index.rst, setup.cfg, tools/coverage-bin/git-annex-backend-XDLRA, tools/coverage-bin/git-remote-datalad-annex, tools/coverage-bin/sitecustomize.py, tools/coverage-bin/with_coverage
=> `datalad-annex::` Git remote helper migration

datalad_next/create_sibling_webdav.py, datalad_next/tests/test_create_sibling_webdav.py
Importantly, there is an end-to-end workflow test now.
=> WebDAV bug fixing and publication dependency setup

datalad_next/tests/test_create_sibling_webdav.py
Could be employed in https://github.com/datalad/datalad-next/pull/4
=> Prepare test for checking export storage on webdav

datalad_next/create_sibling_webdav.py
=> Disable auto-enable of storage-sibling

datalad_next/create_sibling_webdav.py, datalad_next/tests/test_create_sibling_webdav.py
=> Avoid asking users for a "realm" property

datalad_next/credentials.py, datalad_next/credman.py
=> Use better labels for secrets when setting credentials

datalad_next/tests/test_create_sibling_webdav.py
=> Fixup create-sibling-webdav tests

README.md, datalad_next/create_sibling_webdav.py, datalad_next/gitremote/datalad_annex.py, docs/source/conf.py, docs/source/index.rst
Several typos and wording changes. Replacement of template text.
=> Minor changes to docstrings and readme

datalad_next/create_sibling_webdav.py
In response to datalad/datalad-next#17
=> Companion PR for https://github.com/datalad/datalad/pull/6706

datalad_next/patches/push_optimize.py
This is the analog change to https://github.com/datalad/datalad/pull/6869
=> Adjust `push` patch to match -core after fix

changelog.d/20220821_103304_michael.hanke.md, datalad_next/patches/__init__.py, datalad_next/patches/common_cfg.py, datalad_next/tests/test_common_cfg.py
Closes datalad/datalad-next#100
=> Change default of datalad.annex.retry to 1

datalad_next/constraints/__init__.py, datalad_next/constraints/compound.py, datalad_next/constraints/formats.py, datalad_next/constraints/tests/test_cmdarg_validation.py, datalad_next/constraints/tests/test_special_purpose.py
- New `Ensure(Parsed)URL` constraint
- Sketch for command input validation as a unit test
=> Towards command input validation with constraints

datalad_next/backend/tests/test_base.py, datalad_next/constraints/tests/test_cmdarg_validation.py, datalad_next/constraints/tests/test_compound.py, datalad_next/create_sibling_webdav.py, datalad_next/download.py, datalad_next/gitremote/datalad_annex.py, datalad_next/gitremote/tests/test_datalad_annex.py, datalad_next/log.py, datalad_next/patches/annexrepo.py, datalad_next/patches/clone.py, datalad_next/patches/clone_ephemeral.py, datalad_next/patches/clone_utils.py, datalad_next/patches/configuration.py, datalad_next/patches/interface_utils.py, datalad_next/patches/push_optimize.py, datalad_next/patches/runnerthreads.py, datalad_next/patches/tests/test_configuration.py, datalad_next/patches/tests/test_push.py, datalad_next/patches/tests/test_push_to_export_remote.py, datalad_next/tests/test_create_sibling_webdav.py, datalad_next/tests/test_credentials.py, datalad_next/tests/test_credman.py, datalad_next/tests/test_download.py, datalad_next/tests/test_tree.py, datalad_next/tests/test_utils.py, datalad_next/tests/utils.py, datalad_next/tree.py, datalad_next/url_operations/__init__.py, datalad_next/url_operations/file.py, datalad_next/utils.py
=> Import farms

datalad_next/constraints/tests/test_cmdarg_validation.py, datalad_next/create_sibling_webdav.py, datalad_next/credentials.py, datalad_next/download.py, datalad_next/gitremote/datalad_annex.py, datalad_next/interface.py, datalad_next/patches/clone.py, datalad_next/patches/configuration.py, datalad_next/tree.py, datalad_next/utils.py
=> More import consolidation

datalad_next/annexremote/tests/test_uncurl.py, datalad_next/annexremote/uncurl.py, datalad_next/download.py, datalad_next/exceptions.py, datalad_next/patches/siblings.py, datalad_next/url_operations/__init__.py, datalad_next/url_operations/any.py, datalad_next/url_operations/file.py, datalad_next/url_operations/http.py, datalad_next/url_operations/ssh.py, datalad_next/url_operations/tests/test_any.py, datalad_next/url_operations/tests/test_file.py, datalad_next/url_operations/tests/test_http.py, datalad_next/url_operations/tests/test_ssh.py, datalad_next/utils.py
With an implementation for the `file://` handler.
- closes #163
- closes #154
=> uncurl REMOVE and UrlOperations.delete()

datalad_next/constraints/formats.py, datalad_next/constraints/tests/test_special_purpose.py
=> `Ensure(Parsed)URL(match=)` to declare a regex that any URL must match

datalad_next/commands/__init__.py, datalad_next/commands/download.py, docs/source/index.rst
=> `ValidatedInterface` base class ofr uniform parameter validation

setup.cfg
Previously these pieces would be pulled in via other dependencies.
=> Make package dependencies explicit

.github/workflows/docbuild.yml, .github/workflows/test_crippledfs.yml
This should avoid the deprecation warnings.
=> Update actions to newer versions

datalad_next/constraints/base.py, datalad_next/constraints/exceptions.py, datalad_next/constraints/parameter.py, datalad_next/constraints/tests/test_cmdarg_validation.py, datalad_next/constraints/tests/test_compound.py, datalad_next/constraints/tests/test_special_purpose.py
This should put the coming RFs and updates on a more solid foundation.
=> Testing upgrade for `constraints`

datalad_next/constraints/tests/test_compound.py
There was a TODO to test ``EnsureMapping()``'s  ``for_dataset()`` once ``EnsurePath`` learned how to resolve paths against datasets. This change adds testcase to resolve this TODO.
=> TST: add for_dataset testcase to EnsureMapping test

.appveyor.yml, .github/workflows/test_crippledfs.yml, datalad_next/annexremotes/tests/test_uncurl.py, datalad_next/commands/tests/test_download.py, datalad_next/conftest.py, datalad_next/tests/fixtures.py, datalad_next/tests/utils.py, datalad_next/url_operations/tests/test_http.py
=> Spin up httpbin container via pytest fixture

README.md
Small documentation maintenance
=> MNT/DOC: Update readme about webdav fixture

requirements-devel.txt
See https://github.com/datalad/datalad-next/issues/331
=> (Temporarily) use the latest `maint` state of datalad-core for testing

datalad_next/constraints/parameter.py
=> Clarify error message on broken joint-validator implementations

requirements-devel.txt, setup.cfg
=> Depend on 0.18.4 to pull in a fixed datalad-core test battery

datalad_next/annexremotes/uncurl.py, datalad_next/commands/download.py
Plus other doc bits
Closes #150
=> Document how `datalad addurls` can also profit from `uncurl`

datalad_next/types/annexkey.py, datalad_next/types/tests/test_annexkey.py, docs/source/pyutils.rst
=> Establish dedicated `types` module, start with `AnnexKey`

datalad_next/iter_collections/tarfile.py
Forgotten in https://github.com/datalad/datalad-next/pull/367
=> Remove outdated documentation snippet

datalad_next/archive_operations/__init__.py, datalad_next/archive_operations/tarfile.py
Closes #184
Includes a demo `TarArchiveOperations`
Tests will have to be pulled from #372 in a later PR.
=> `datalad_next.archive_operations`

datalad_next/iter_collections/tarfile.py, datalad_next/iter_collections/tests/test_iterzip.py, datalad_next/iter_collections/zipfile.py
Extracted bolt-on from https://github.com/datalad/datalad-next/pull/372
=> `iter_zip()`

datalad_next/iter_collections/directory.py, datalad_next/iter_collections/utils.py
Can be reused by other derived classes.
=> Establish `FileSystemItem.from_path()`

changelog.d/20230609_074319_michael.hanke_dla.md, datalad_next/gitremotes/datalad_annex.py
=> Companion of https://github.com/datalad/datalad-osf/pull/176

.appveyor.yml
=> Fix Appveyor's virtualenv setup

CONTRIBUTING.md
=> More guidelines on test implementations

.appveyor.yml
=> Update CI runs to use min Python version 3.8

changelog.d/20230928_123529_michael.hanke_doc_pr455.md
Ping @christian-monch for awareness.
=> Add changelog item missing from #455

datalad_next/runners/__init__.py
Closes #466
ping @christian-monch
=> Have a documentation entrypoint for runner-tooling

.github/workflows/mypy.yml, datalad_next/constraints/basic.py, datalad_next/constraints/exceptions.py, datalad_next/credman/manager.py, datalad_next/url_operations/http.py, datalad_next/utils/requests_auth.py
`mypy` run shows that the situation is better, but is overall still bad.
=> Fix few trivial type annotation bugs

CONTRIBUTING.md, datalad_next/commands/tests/test_credentials.py, datalad_next/commands/tests/test_download.py, datalad_next/constraints/tests/test_special_purpose.py, datalad_next/gitremotes/tests/test_datalad_annex.py, datalad_next/iter_collections/tests/test_itergitworktree.py, datalad_next/iter_collections/tests/test_itertar.py, datalad_next/patches/tests/test_create_sibling_gitlab.py, datalad_next/patches/tests/test_push.py
- comes from datalad-core
- would imply substantial complexity to remove
- is potentially useful (server logs)
Closes #503
=> Reduce test battery noise

datalad_next/url_operations/ssh.py
This PR fixes #594
It modifies the implementation of `SshUrlOperations` so that it catches expected exceptions before they leave the `iterable_subprocess`-context. This leads to a proper shutdown of the ssh-subprocess, via closing its stdin, and to a reliable signaling of the return code of the remote command.
The latter would not always be the case if the `iterable_subprocess`-context is left with an exception, because that triggers a `terminate()` on the shell process, and the exit code of the ssh-subprocess will reflect this termination.
=> Ensure that the return-value of ssh-subprocess is used when `StopIteration` is raised.

datalad_next/iter_collections/utils.py
at least until we have a thought-through strategy for cache invalidation.
Closes #591
=> Do not cache PathBasedItem.path

CONTRIBUTING.md, datalad_next/annexremotes/tests/test_uncurl.py, datalad_next/commands/__init__.py, datalad_next/commands/create_sibling_webdav.py, datalad_next/commands/credentials.py, datalad_next/commands/download.py, datalad_next/commands/status.py, datalad_next/commands/tests/test_ls_file_collection.py, datalad_next/commands/tests/test_status.py, datalad_next/commands/tree.py, datalad_next/constraints/__init__.py, datalad_next/constraints/exceptions.py, datalad_next/patches/interface_utils.py, docs/source/developer_guide/constraints.rst
See https://github.com/datalad/datalad-next/issues/613
=> Define public API of `datalad_next.constraints`

datalad_next/annexremotes/archivist.py, datalad_next/archive_operations/__init__.py, datalad_next/archive_operations/base.py, datalad_next/archive_operations/tarfile.py, datalad_next/archive_operations/zipfile.py
See https://github.com/datalad/datalad-next/issues/613
=> Define public API of `datalad_next.archive_operations`

CONTRIBUTING.md, README.md, changelog.d/20240205_165507_michael.hanke_bf_613.md
=> Document rules for declaring the "public" datalad-next API

datalad_next/annexremotes/tests/test_uncurl.py, datalad_next/annexremotes/uncurl.py
Thanks to @yarikoptic for suggesting the missing piece to complete this PR.
=> Type annotation for `uncurl`

datalad_next/shell/operations/posix.py, datalad_next/shell/tests/test_shell.py
This PR adds a progress callback to the method `datalad_next.shell.operations.posix.download`. It also extends the tests to verify that progress downloads are called for upload- and download-operations.
The PR also corrects a faulty description in the doc-string of `datalad_next.shell.operations.posix.download`.
=> Add progress-callback to `datalad_next.shell.operations.posix.download`

changelog.d/20240507_083933_michael.hanke_changelog.md, changelog.d/20240507_085430_michael.hanke_changelog.md, changelog.d/20240507_085747_michael.hanke_changelog.md, changelog.d/20240507_090109_michael.hanke_changelog.md, changelog.d/20240507_090725_michael.hanke_changelog.md
=> Add missing changelog snippets for upcoming release

datalad_next/patches/replace_sshremoteio.py, datalad_next/shell/operations/posix.py
=> consolidate keyword argument indicator

CONTRIBUTING.md, datalad_next/shell/__init__.py, datalad_next/shell/operations/posix.py, datalad_next/shell/shell.py
This PR adds a number of additional shell examples and tips. It also links the examples in the top-level package document.
Fixes #656
=> Add shell-examples

CHANGELOG.md
One PR was forgotten.
Refs: https://github.com/datalad/datalad-next/pull/696
=> chore(changelog): add missing, non-conventional change

.changelog.md.j2, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, CONTRIBUTING.md, pyproject.toml
Update the generation template also.
=> style(changelog): keep entries be a single line

datalad_next/iter_collections/tests/test_itergitworktree.py
Previously, this iterator has only been tested implicitly.
=> test(iter_submodules): add dedicated test

datalad_next/iter_collections/gitworktree.py
Closes: https://github.com/datalad/datalad-next/issues/722
=> doc(`iter_gitworktree`): add documentation on `pathspecs` argument

datalad_next/itertools/align_pattern.py
This is a backport from `datasalad`  [PR datalad/datasalad#33](https://github.com/datalad/datasalad/pull/33)
=> Fix type annotations in `alig_pattern`
